<?php
// Init
$sql = array();

// Create Log Table in Database
$sql[] = 'CREATE TABLE IF NOT EXISTS '.DB_PREFIX.'lelong_sync_log('.
		 '`log_id` int(20) NOT NULL AUTO_INCREMENT,'.
         '`product_id` int(15) NOT NULL,'.
         '`type` char(1) NOT NULL DEFAULT "D" COMMENT "D:Direct;Q:Queue",'.
         '`status` varchar(6) NOT NULL,'.
         '`product_json` text NOT NULL,'.
         '`response` varchar(255) NOT NULL,'.
         '`sync_date` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,'.
         'PRIMARY KEY (`log_id`),'.
         'KEY `product_id` (`product_id`)'.
	');';


// Create Queue Table in Database
$sql[] = 'CREATE TABLE IF NOT EXISTS '.DB_PREFIX.'lelong_sync_queue('.
    '`queue_id` int(10) NOT NULL AUTO_INCREMENT,'.
    '`product_id` int(15) NOT NULL,'.
    '`product_json` text NOT NULL,'.
    '`status` char(1) NOT NULL,'.
    '`add_date` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,'.
    '`last_update` timestamp NOT NULL DEFAULT "0000-00-00 00:00:00",'.
    '`retry_count` int(1) DEFAULT NULL,'.
    'PRIMARY KEY (`queue_id`)'.
	');';

// Create Product Table in Database
$sql[] = 'CREATE TABLE IF NOT EXISTS '.DB_PREFIX.'lelong_product('.
    '`product_id` int(15) NOT NULL,'.
    '`product_json` text NOT NULL,'.
    '`options_json` text NOT NULL,'.
    '`last_update` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,'.
    'PRIMARY KEY (`product_id`)'.
');';

//Create Error Log Table in Database
$sql[] = 'CREATE TABLE IF NOT EXISTS '.DB_PREFIX.'lelong_error_log ('.
	  '`log_id` int(10) NOT NULL AUTO_INCREMENT,'.
	  '`log_type` varchar(255) NOT NULL,'.
	  '`product_id` int(10) NOT NULL,'.
	  '`message` text NOT NULL,'.
	  '`notified` tinyint(1) NOT NULL,'.
	  '`create_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,'.
	  'PRIMARY KEY (`log_id`)'.
	  ');';
$sql[] = 'CREATE TABLE IF NOT EXISTS '.DB_PREFIX.'lelong_category ('.
  '`category_id` int(10) NOT NULL,'.
  '`name` varchar(255) NOT NULL,'.
  '`create_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,'.
  '`last_update` datetime NOT NULL,'.
  'PRIMARY KEY (`category_id`)'.
')';

$sql[] = 'CREATE TABLE IF NOT EXISTS '.DB_PREFIX.'lelong_store_category ('.
  '`category_id` int(10) NOT NULL,'.
  '`name` varchar(255) NOT NULL,'.
  '`parent_category_id` int(10) NOT NULL,'.
  '`level` int(10) NOT NULL,'.
  '`create_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,'.
  '`last_update` datetime NOT NULL,'.
  'PRIMARY KEY (`category_id`)'.
')';
  
$sql[] = "INSERT INTO ".DB_PREFIX."lelong_category (`category_id`, `name`, `create_time`, `last_update`) VALUES
(23, 'Arts, Antiques & Collectibles > Antiques', NOW(), NOW()),
(24, 'Arts, Antiques & Collectibles > Arts', NOW(), NOW()),
(25, 'Arts, Antiques & Collectibles > Asian Arts', NOW(), NOW()),
(27, 'Arts, Antiques & Collectibles > Coins', NOW(), NOW()),
(28, 'Arts, Antiques & Collectibles > Pottery', NOW(), NOW()),
(29, 'Arts, Antiques & Collectibles > Porcelain', NOW(), NOW()),
(30, 'Arts, Antiques & Collectibles > Clock & Watches', NOW(), NOW()),
(31, 'Arts, Antiques & Collectibles > Glass', NOW(), NOW()),
(32, 'Arts, Antiques & Collectibles > Hand Crafted Arts', NOW(), NOW()),
(33, 'Arts, Antiques & Collectibles > Metalware', NOW(), NOW()),
(34, 'Arts, Antiques & Collectibles > Furniture', NOW(), NOW()),
(38, 'Cars & Transport > Van', NOW(), NOW()),
(39, 'Cars & Transport > Boats', NOW(), NOW()),
(41, 'Cars & Transport > Vintage & Collect Cars', NOW(), NOW()),
(43, 'Books & Comics > Bestseller', NOW(), NOW()),
(44, 'Books & Comics > Business', NOW(), NOW()),
(45, 'Books & Comics > Textbooks', NOW(), NOW()),
(46, 'Books & Comics > Audio Books', NOW(), NOW()),
(47, 'Books & Comics > Computers & IT', NOW(), NOW()),
(49, 'Books & Comics > Journal', NOW(), NOW()),
(50, 'Books & Comics > Entertainment', NOW(), NOW()),
(57, 'Computer & Software > Hardware > Mac / Apple', NOW(), NOW()),
(58, 'Computer & Software > Hardware > Cable', NOW(), NOW()),
(59, 'Computer & Software > Hardware > Component', NOW(), NOW()),
(62, 'Computer & Software > Hardware > Drive > Hard Disk', NOW(), NOW()),
(63, 'Computer & Software > Hardware > Drive > Floppy Drive', NOW(), NOW()),
(64, 'Computer & Software > Hardware > Drive > Zip Drive', NOW(), NOW()),
(65, 'Computer & Software > Hardware > Drive > Super Drive', NOW(), NOW()),
(71, 'Computer & Software > Hardware > Flat Screen', NOW(), NOW()),
(75, 'Computer & Software > Hardware > PC & Desktop', NOW(), NOW()),
(77, 'Computer & Software > Hardware > Server', NOW(), NOW()),
(79, 'Computer & Software > Hardware > Web Devices', NOW(), NOW()),
(82, 'Computer & Software > Software > PC > Games', NOW(), NOW()),
(83, 'Computer & Software > Software > PC > Application', NOW(), NOW()),
(84, 'Computer & Software > Software > PC > Operating System', NOW(), NOW()),
(85, 'Computer & Software > Software > PC > NT', NOW(), NOW()),
(86, 'Computer & Software > Software > PC > Programming', NOW(), NOW()),
(87, 'Computer & Software > Software > PC > Database', NOW(), NOW()),
(88, 'Computer & Software > Software > Mac', NOW(), NOW()),
(89, 'Computer & Software > Software > Unix', NOW(), NOW()),
(91, 'Computer & Software > Software > Linux > Games', NOW(), NOW()),
(92, 'Computer & Software > Software > Linux > Application', NOW(), NOW()),
(93, 'Computer & Software > Services > Web Hosting', NOW(), NOW()),
(94, 'Computer & Software > Services > Web Design', NOW(), NOW()),
(95, 'Computer & Software > Services > Programming', NOW(), NOW()),
(96, 'Computer & Software > Services > Servicing', NOW(), NOW()),
(97, 'Computer & Software > Services > Rental', NOW(), NOW()),
(98, 'Computer & Software > Services > Repair', NOW(), NOW()),
(99, 'Computer & Software > Services > Education', NOW(), NOW()),
(100, 'Computer & Software > Domain Name > Malaysia', NOW(), NOW()),
(101, 'Computer & Software > Domain Name > International', NOW(), NOW()),
(104, 'Computer & Software > PDAs > Palm OS > Palm VX', NOW(), NOW()),
(105, 'Computer & Software > PDAs > Palm OS > Palm 3C', NOW(), NOW()),
(107, 'Computer & Software > PDAs > Palm OS > Visor', NOW(), NOW()),
(109, 'Computer & Software > PDAs > Windows CE > Casiopiea', NOW(), NOW()),
(111, 'Computer & Software > PDAs > Windows CE > Aero', NOW(), NOW()),
(112, 'Computer & Software > PDAs > Psion', NOW(), NOW()),
(114, 'Electronics & Appliances > Audio > CD Player', NOW(), NOW()),
(115, 'Electronics & Appliances > Audio > Discman', NOW(), NOW()),
(116, 'Electronics & Appliances > Audio > Mini Disc', NOW(), NOW()),
(117, 'Electronics & Appliances > Audio > Stereo', NOW(), NOW()),
(118, 'Electronics & Appliances > Audio > Hi Fi', NOW(), NOW()),
(120, 'Electronics & Appliances > Home & Kitchen > Air Conditioners', NOW(), NOW()),
(121, 'Electronics & Appliances > Home & Kitchen > Blenders,Mixers & Grinders', NOW(), NOW()),
(122, 'Electronics & Appliances > Home & Kitchen > Coffee Maker', NOW(), NOW()),
(123, 'Electronics & Appliances > Home & Kitchen > Refrigerator', NOW(), NOW()),
(124, 'Electronics & Appliances > Home & Kitchen > Vacuum Cleaner & Steam Cleaner', NOW(), NOW()),
(125, 'Electronics & Appliances > Home & Kitchen > Rice Cooker', NOW(), NOW()),
(126, 'Electronics & Appliances > Home & Kitchen > Kettle', NOW(), NOW()),
(127, 'Electronics & Appliances > Home & Kitchen > Slow Cooker & Steamer', NOW(), NOW()),
(128, 'Electronics & Appliances > VCD Player', NOW(), NOW()),
(129, 'Electronics & Appliances > VCR PLayer', NOW(), NOW()),
(130, 'Electronics & Appliances > DVD Player', NOW(), NOW()),
(131, 'Electronics & Appliances > Laser Disc Player', NOW(), NOW()),
(138, 'Electronics & Appliances > Cameras > Accessories', NOW(), NOW()),
(140, 'Electronics & Appliances > Calculators', NOW(), NOW()),
(141, 'Electronics & Appliances > Electronic Parts', NOW(), NOW()),
(142, 'Electronics & Appliances > Test Equipment', NOW(), NOW()),
(145, 'Sports & Recreation > Exercise Equipment', NOW(), NOW()),
(146, 'Sports & Recreation > Game Table', NOW(), NOW()),
(148, 'Sports & Recreation > Racquet Sports', NOW(), NOW()),
(149, 'Sports & Recreation > Sports Wear', NOW(), NOW()),
(158, 'Toys & Games > Game Console > Sega > Dreamcast', NOW(), NOW()),
(161, 'Toys & Games > Game Console > Sony > Playstation 2', NOW(), NOW()),
(163, 'Toys & Games > Game Console > Handheld', NOW(), NOW()),
(164, 'Toys & Games > Game Console > Atari', NOW(), NOW()),
(165, 'Toys & Games > Game Console > PC Games', NOW(), NOW()),
(166, 'Toys & Games > Action Figures', NOW(), NOW()),
(168, 'Toys & Games > Fast Food Toys > Hello Kitty', NOW(), NOW()),
(169, 'Toys & Games > Fast Food Toys > McDonald', NOW(), NOW()),
(170, 'Toys & Games > Fast Food Toys > KFC', NOW(), NOW()),
(171, 'Toys & Games > Fast Food Toys > Furby', NOW(), NOW()),
(172, 'Toys & Games > Building Set', NOW(), NOW()),
(173, 'Toys & Games > Doll', NOW(), NOW()),
(175, 'Toys & Games > TV Characters', NOW(), NOW()),
(177, 'Toys & Games > Model > Air Craft', NOW(), NOW()),
(178, 'Toys & Games > Model > Cars', NOW(), NOW()),
(179, 'Toys & Games > Model > Boats', NOW(), NOW()),
(180, 'Toys & Games > Model > Horses', NOW(), NOW()),
(181, 'Toys & Games > Model > Motorcycles', NOW(), NOW()),
(183, 'Movies & Video > DVD', NOW(), NOW()),
(184, 'Movies & Video > Laser Disc', NOW(), NOW()),
(185, 'Movies & Video > VCD', NOW(), NOW()),
(186, 'Movies & Video > Video Tape', NOW(), NOW()),
(187, 'Movies & Video > Tickets', NOW(), NOW()),
(189, 'Music & Song > CDs', NOW(), NOW()),
(190, 'Music & Song > Records', NOW(), NOW()),
(191, 'Music & Song > Tapes', NOW(), NOW()),
(193, 'Music & Song > Magazine', NOW(), NOW()),
(194, 'Music & Song > Lessons', NOW(), NOW()),
(195, 'Music & Song > Concert Ticket', NOW(), NOW()),
(200, 'Phone & Tablet > Handphone > Dual Band', NOW(), NOW()),
(201, 'Phone & Tablet > Handphone > Triband', NOW(), NOW()),
(202, 'Phone & Tablet > Handphone > Analog', NOW(), NOW()),
(209, 'Phone & Tablet > Pagers', NOW(), NOW()),
(211, 'Phone & Tablet > Answering Machine', NOW(), NOW()),
(212, 'Phone & Tablet > Fax', NOW(), NOW()),
(217, 'Fashion > Men > Clothing > Sports Apparel', NOW(), NOW()),
(218, 'Fashion > Men > Clothing > T-Shirts & Polos', NOW(), NOW()),
(220, 'Fashion > General', NOW(), NOW()),
(225, 'Beauty & Personal Care > Perfumes > For Him', NOW(), NOW()),
(226, 'Beauty & Personal Care > Perfumes > For Her', NOW(), NOW()),
(227, 'Beauty & Personal Care > Cosmetic', NOW(), NOW()),
(229, 'Beauty & Personal Care > Wedding', NOW(), NOW()),
(231, 'Jewellery & Accessories > Others', NOW(), NOW()),
(232, 'Jewellery & Accessories > Gold', NOW(), NOW()),
(234, 'Jewellery & Accessories > Silver', NOW(), NOW()),
(236, 'Jewellery & Accessories > Bracelets', NOW(), NOW()),
(237, 'Jewellery & Accessories > Earrings', NOW(), NOW()),
(239, 'Food & Beverages > General', NOW(), NOW()),
(240, 'Food & Beverages > Restaurant', NOW(), NOW()),
(242, 'Travel, Tours & Hotel > Travel & Vacation > Local', NOW(), NOW()),
(243, 'Travel, Tours & Hotel > Travel & Vacation > International', NOW(), NOW()),
(245, 'Travel, Tours & Hotel > Ticket > Air Tickets', NOW(), NOW()),
(246, 'Travel, Tours & Hotel > Ticket > Train', NOW(), NOW()),
(247, 'Travel, Tours & Hotel > Ticket > Cruise', NOW(), NOW()),
(248, 'Travel, Tours & Hotel > Hotel & Accomodation', NOW(), NOW()),
(249, 'Travel, Tours & Hotel > Luggage & Accessories', NOW(), NOW()),
(250, 'Travel, Tours & Hotel > Guide Books', NOW(), NOW()),
(252, 'Home & Gardening > Carpets', NOW(), NOW()),
(253, 'Home & Gardening > Power Tools', NOW(), NOW()),
(255, 'Home & Gardening > Furniture', NOW(), NOW()),
(257, 'Home & Gardening > Furnishing > Granite', NOW(), NOW()),
(258, 'Home & Gardening > Furnishing > Marble', NOW(), NOW()),
(259, 'Home & Gardening > Furnishing > Slate', NOW(), NOW()),
(260, 'Home & Gardening > Furnishing > Lamps & Lighting', NOW(), NOW()),
(261, 'Home & Gardening > Furnishing > Pets', NOW(), NOW()),
(263, 'House & Property > Land', NOW(), NOW()),
(264, 'House & Property > Condominium', NOW(), NOW()),
(265, 'House & Property > Apartment', NOW(), NOW()),
(266, 'House & Property > Double Storey', NOW(), NOW()),
(267, 'House & Property > Link House', NOW(), NOW()),
(269, 'House & Property > Single Storey', NOW(), NOW()),
(270, 'House & Property > Office Building', NOW(), NOW()),
(273, 'B2B & Industrial Products > Factory Surplus', NOW(), NOW()),
(275, 'B2B & Industrial Products > Machinery', NOW(), NOW()),
(279, 'Toys & Games > Model > Model Railroad', NOW(), NOW()),
(280, 'Arts, Antiques & Collectibles > Bank Note', NOW(), NOW()),
(281, 'Sports & Recreation > Sport Spectacles', NOW(), NOW()),
(282, 'Music & Song > Instrument > Guitar', NOW(), NOW()),
(283, 'Music & Song > Instrument > Piano', NOW(), NOW()),
(284, 'Home & Gardening > Pets', NOW(), NOW()),
(288, 'Books & Comics > Magazine > Management', NOW(), NOW()),
(289, 'Books & Comics > Magazine > Entertainment', NOW(), NOW()),
(290, 'Books & Comics > Magazine > Computer', NOW(), NOW()),
(291, 'Computer & Software > Hardware > Video Display > General', NOW(), NOW()),
(292, 'Computer & Software > Hardware > Video Display > Video Capture', NOW(), NOW()),
(293, 'Phone & Tablet > Handphone > GSM', NOW(), NOW()),
(295, 'Computer & Software > Hardware > Drive > CD-Rom', NOW(), NOW()),
(296, 'Computer & Software > Hardware > Drive > CD Writer', NOW(), NOW()),
(297, 'Computer & Software > Hardware > Drive > CD Duplicator', NOW(), NOW()),
(298, 'Computer & Software > Hardware > Modem > Internal', NOW(), NOW()),
(299, 'Computer & Software > Hardware > Modem > External', NOW(), NOW()),
(300, 'Computer & Software > Hardware > Modem > USB', NOW(), NOW()),
(301, 'Books & Comics > Stationery', NOW(), NOW()),
(302, 'Phone & Tablet > Walkie-Talkie', NOW(), NOW()),
(303, 'Computer & Software > Hardware > Input Devices > Keyboard', NOW(), NOW()),
(305, 'Electronics & Appliances > Audio > Radio Cassette', NOW(), NOW()),
(307, 'Arts, Antiques & Collectibles > Trading Card Games', NOW(), NOW()),
(308, 'Arts, Antiques & Collectibles > Writting Instruments', NOW(), NOW()),
(309, 'Books & Comics > Travel Book', NOW(), NOW()),
(312, 'Arts, Antiques & Collectibles > Misc Collectibles', NOW(), NOW()),
(313, 'Sports & Recreation > Golf > Club Memberships', NOW(), NOW()),
(314, 'Sports & Recreation > Skates & SkateBoards', NOW(), NOW()),
(315, 'Computer & Software > Hardware > Modem > PC Card', NOW(), NOW()),
(316, 'Music & Song > Instrument > Organ', NOW(), NOW()),
(317, 'Computer & Software > Hardware > PC Audio Speaker > Speaker', NOW(), NOW()),
(318, 'Computer & Software > Hardware > PC Audio Speaker > Subwoofer', NOW(), NOW()),
(319, 'Computer & Software > Hardware > PC Audio Speaker > Sound card', NOW(), NOW()),
(321, 'Sports & Recreation > Fishing > Rods', NOW(), NOW()),
(322, 'Sports & Recreation > Fishing > Reels', NOW(), NOW()),
(323, 'Sports & Recreation > Fishing > Accessories', NOW(), NOW()),
(325, 'Electronics & Appliances > Audio > Amplifier', NOW(), NOW()),
(327, 'Sports & Recreation > Camping Equipment > Tents', NOW(), NOW()),
(328, 'Sports & Recreation > Camping Equipment > General', NOW(), NOW()),
(329, 'Sports & Recreation > Camping Equipment > Bags', NOW(), NOW()),
(330, 'House & Property > Commercial Shoplot', NOW(), NOW()),
(331, 'House & Property > Student House', NOW(), NOW()),
(332, 'House & Property > Office Space', NOW(), NOW()),
(333, 'House & Property > Factory', NOW(), NOW()),
(334, 'House & Property > Warehouse', NOW(), NOW()),
(335, 'Electronics & Appliances > Audio > Speaker', NOW(), NOW()),
(337, 'Arts, Antiques & Collectibles > Trading Cards > Pokemon', NOW(), NOW()),
(339, 'Sports & Recreation > Snooker & Billiard > General', NOW(), NOW()),
(340, 'Sports & Recreation > Snooker & Billiard > Table', NOW(), NOW()),
(341, 'Sports & Recreation > Snooker & Billiard > Snooker Cue', NOW(), NOW()),
(343, 'Computer & Software > Game > Joystick', NOW(), NOW()),
(344, 'Computer & Software > Game > Racing Wheel', NOW(), NOW()),
(345, 'Computer & Software > Game > Accessories', NOW(), NOW()),
(346, 'B2B & Industrial Products > Office Equipment > General Equipment', NOW(), NOW()),
(347, 'B2B & Industrial Products > Office Equipment > Consumables', NOW(), NOW()),
(348, 'Computer & Software > Web Cam', NOW(), NOW()),
(350, 'Beauty & Personal Care > Medical', NOW(), NOW()),
(352, 'General & Misc > Others', NOW(), NOW()),
(354, 'General & Misc > Medical Equipment', NOW(), NOW()),
(355, 'Books & Comics > Literature', NOW(), NOW()),
(356, 'Books & Comics > Comics', NOW(), NOW()),
(357, 'Sports & Recreation > Golf > Golf Bags', NOW(), NOW()),
(359, 'Sports & Recreation > Golf > Woods', NOW(), NOW()),
(360, 'Sports & Recreation > Golf > Drivers', NOW(), NOW()),
(362, 'Sports & Recreation > Golf > Irons - Set', NOW(), NOW()),
(364, 'Sports & Recreation > Golf > Others', NOW(), NOW()),
(365, 'Sports & Recreation > Golf > Putters', NOW(), NOW()),
(366, 'Sports & Recreation > Golf > Accessories', NOW(), NOW()),
(369, 'Electronics & Appliances > Mp3 Player', NOW(), NOW()),
(370, 'Computer & Software > Hardware > Barebone System', NOW(), NOW()),
(372, 'Books & Comics > Fiction > Romance', NOW(), NOW()),
(373, 'Fashion > Women > Accessories > Eyewear', NOW(), NOW()),
(374, 'Toys & Games > Pokemon', NOW(), NOW()),
(375, 'Computer & Software > PDAs > Pocket Viewer', NOW(), NOW()),
(376, 'Computer & Software > Accessories > Data Switch', NOW(), NOW()),
(377, 'Computer & Software > Accessories > General', NOW(), NOW()),
(378, 'Sports & Recreation > Bowling', NOW(), NOW()),
(380, 'Rental, To Let & For Hire > Apartment', NOW(), NOW()),
(381, 'Rental, To Let & For Hire > Student House', NOW(), NOW()),
(382, 'Rental, To Let & For Hire > Room', NOW(), NOW()),
(383, 'Rental, To Let & For Hire > House', NOW(), NOW()),
(384, 'Rental, To Let & For Hire > Equipment', NOW(), NOW()),
(385, 'Rental, To Let & For Hire > Lorry & Truck', NOW(), NOW()),
(386, 'Rental, To Let & For Hire > Cars', NOW(), NOW()),
(388, 'Electronics & Appliances > Audio > Commercial Sound Systems', NOW(), NOW()),
(389, 'Computer & Software > Hardware > Memory > EDO Ram', NOW(), NOW()),
(390, 'Computer & Software > Hardware > Memory > SDRAM', NOW(), NOW()),
(391, 'Computer & Software > Hardware > Memory > Notebook Ram', NOW(), NOW()),
(392, 'Home & Gardening > Furnishing > Interior', NOW(), NOW()),
(393, 'Sports & Recreation > Pool Table', NOW(), NOW()),
(394, 'Electronics & Appliances > Home & Kitchen > Standing Fan', NOW(), NOW()),
(395, 'Electronics & Appliances > Home & Kitchen > Washing Machine', NOW(), NOW()),
(396, 'Computer & Software > Scanner', NOW(), NOW()),
(397, 'B2B & Industrial Products > Office Equipment > Pen', NOW(), NOW()),
(398, 'Sports & Recreation > Club Membership', NOW(), NOW()),
(399, 'Computer & Software > Projector', NOW(), NOW()),
(400, 'Electronics & Appliances > Electronic Component', NOW(), NOW()),
(401, 'Music & Song > Instrument > Others', NOW(), NOW()),
(402, 'Music & Song > Instrument > Drum', NOW(), NOW()),
(403, 'Computer & Software > PDAs > Pocket PC', NOW(), NOW()),
(405, 'Home & Gardening > Others', NOW(), NOW()),
(406, 'Books & Comics > Self Improvement', NOW(), NOW()),
(407, 'Electronics & Appliances > Home & Kitchen > Microwave', NOW(), NOW()),
(408, 'Electronics & Appliances > Home & Kitchen > Kitchen Appliances', NOW(), NOW()),
(410, 'Beauty & Personal Care > Health & Wellness > Others', NOW(), NOW()),
(411, 'B2B & Industrial Products > Services', NOW(), NOW()),
(412, 'B2B & Industrial Products > Others', NOW(), NOW()),
(413, 'Toys & Games > Video Game > Joystick', NOW(), NOW()),
(414, 'Toys & Games > Video Game > Memory Card', NOW(), NOW()),
(415, 'Toys & Games > Video Game > Game console', NOW(), NOW()),
(416, 'Toys & Games > Video Game > Others', NOW(), NOW()),
(417, 'B2B & Industrial Products > Industrial Products', NOW(), NOW()),
(418, 'Computer & Software > Hardware > Printer > Laser Printer', NOW(), NOW()),
(419, 'Computer & Software > Hardware > Printer > Ink Jet', NOW(), NOW()),
(420, 'Computer & Software > Hardware > Printer > Dot Matrix', NOW(), NOW()),
(421, 'Computer & Software > Hardware > Printer > Ink Refill', NOW(), NOW()),
(423, 'Computer & Software > Hardware > Printer > General', NOW(), NOW()),
(426, 'B2B & Industrial Products > Heavy Equipment', NOW(), NOW()),
(428, 'Computer & Software > PDAs > Windows CE > Philip Nino', NOW(), NOW()),
(429, 'Sports & Recreation > Golf > Gifts', NOW(), NOW()),
(430, 'Sports & Recreation > Golf > Caps', NOW(), NOW()),
(432, 'Sports & Recreation > Golf > Balls', NOW(), NOW()),
(433, 'Sports & Recreation > Golf > Bag Covers', NOW(), NOW()),
(434, 'Sports & Recreation > Golf > Books', NOW(), NOW()),
(435, 'Sports & Recreation > Golf > Carts', NOW(), NOW()),
(436, 'Sports & Recreation > Golf > Head Covers', NOW(), NOW()),
(437, 'Sports & Recreation > Golf > Irons - Individual', NOW(), NOW()),
(438, 'Sports & Recreation > Golf > Package Sets', NOW(), NOW()),
(439, 'Sports & Recreation > Golf > Wedges', NOW(), NOW()),
(441, 'Books & Comics > Engineering', NOW(), NOW()),
(443, 'Music & Song > Band Merchandise', NOW(), NOW()),
(452, 'Travel, Tours & Hotel > Ticket > Bus Tickets', NOW(), NOW()),
(453, 'General & Misc > Festival Cards', NOW(), NOW()),
(457, 'Computer & Software > Hardware > Memory > RDRam', NOW(), NOW()),
(459, 'Arts, Antiques & Collectibles > Stamps > Asia', NOW(), NOW()),
(460, 'Arts, Antiques & Collectibles > Stamps > Europe', NOW(), NOW()),
(461, 'Arts, Antiques & Collectibles > Stamps > First Day Covers', NOW(), NOW()),
(462, 'Arts, Antiques & Collectibles > Stamps > Africa', NOW(), NOW()),
(463, 'Arts, Antiques & Collectibles > Stamps > South America', NOW(), NOW()),
(464, 'Arts, Antiques & Collectibles > Stamps > North America', NOW(), NOW()),
(465, 'Arts, Antiques & Collectibles > Stamps > Middle East', NOW(), NOW()),
(466, 'Arts, Antiques & Collectibles > Stamps > Others', NOW(), NOW()),
(467, 'Arts, Antiques & Collectibles > Stamps > Malaysia', NOW(), NOW()),
(468, 'Arts, Antiques & Collectibles > Stamps > Tropical', NOW(), NOW()),
(469, 'Arts, Antiques & Collectibles > Key Chain', NOW(), NOW()),
(470, 'Computer & Software > PDAs > Windows CE > Jornada', NOW(), NOW()),
(471, 'Cars & Transport > Car Number Plate', NOW(), NOW()),
(472, 'Fashion > Women > Accessories > Hats, Caps & Beannie', NOW(), NOW()),
(473, 'Electronics & Appliances > General > Batteries', NOW(), NOW()),
(475, 'Electronics & Appliances > Audio > Microphone', NOW(), NOW()),
(476, 'Electronics & Appliances > Audio > Portable Sound System', NOW(), NOW()),
(477, 'Computer & Software > Game > Game Pad', NOW(), NOW()),
(478, 'Fashion > Women > Clothing > Coats & Jackets', NOW(), NOW()),
(479, 'Rental, To Let & For Hire > Commercial Shoplot', NOW(), NOW()),
(480, 'Movies & Video > Movie Collectibles & Merchandise', NOW(), NOW()),
(481, 'Movies & Video > Others', NOW(), NOW()),
(482, 'Arts, Antiques & Collectibles > Poster', NOW(), NOW()),
(483, 'House & Property > Flat', NOW(), NOW()),
(485, 'Computer & Software > Hardware > CPU > Cooler - Heat Sink & Fan', NOW(), NOW()),
(486, 'B2B & Industrial Products > Office Equipment > Photostat Machine', NOW(), NOW()),
(489, 'Services > Child Care', NOW(), NOW()),
(490, 'Services > Tuition', NOW(), NOW()),
(491, 'Services > Repair & Maintenance', NOW(), NOW()),
(492, 'Computer & Software > PDAs > Palm OS > Palm M100/105', NOW(), NOW()),
(493, 'Computer & Software > Hardware > Drive > Tape Drive', NOW(), NOW()),
(494, 'Books & Comics > Fiction > Science', NOW(), NOW()),
(495, 'Books & Comics > Fiction > Adventure', NOW(), NOW()),
(496, 'Computer & Software > PDAs > Palm OS > Sony Clie', NOW(), NOW()),
(497, 'Computer & Software > PDAs > Palm OS > Palm m500', NOW(), NOW()),
(498, 'Computer & Software > PDAs > Palm OS > Palm m505', NOW(), NOW()),
(500, 'Arts, Antiques & Collectibles > Miniatures', NOW(), NOW()),
(502, 'Computer & Software > PDAs > Royal daVinci', NOW(), NOW()),
(504, 'Food & Beverages > Beverages', NOW(), NOW()),
(505, 'Computer & Software > Hardware > Memory > Memory Card', NOW(), NOW()),
(507, 'Computer & Software > Hardware > Power Supply', NOW(), NOW()),
(508, 'Home & Gardening > Home Services > Aircondition servicing', NOW(), NOW()),
(509, 'Home & Gardening > Home Services > Plumbing', NOW(), NOW()),
(510, 'Home & Gardening > Home Services > Electrical', NOW(), NOW()),
(511, 'Cars & Transport > Parts & Accessories > Rims and Tyres', NOW(), NOW()),
(513, 'Cars & Transport > Parts & Accessories > Absorbers & Springs', NOW(), NOW()),
(517, 'Cars & Transport > Parts & Accessories > Engines & Components', NOW(), NOW()),
(518, 'Cars & Transport > Parts & Accessories > Air Fuel Delivery', NOW(), NOW()),
(519, 'Cars & Transport > Parts & Accessories > Chassis & Suspension', NOW(), NOW()),
(520, 'Cars & Transport > Parts & Accessories > Other Parts', NOW(), NOW()),
(521, 'Cars & Transport > Parts & Accessories > Seats & Interiors', NOW(), NOW()),
(522, 'Cars & Transport > Parts & Accessories > Exterior Body', NOW(), NOW()),
(523, 'Cars & Transport > Parts & Accessories > Lighting', NOW(), NOW()),
(524, 'Cars & Transport > Parts & Accessories > Gauges & Electronics', NOW(), NOW()),
(526, 'Arts, Antiques & Collectibles > Figurines & Dolls', NOW(), NOW()),
(527, 'Books & Comics > Fiction > Mystery', NOW(), NOW()),
(528, 'Arts, Antiques & Collectibles > Trading Cards > Harry Potter', NOW(), NOW()),
(529, 'Computer & Software > Computer Storage > CD Media', NOW(), NOW()),
(530, 'Computer & Software > Computer Storage > Others', NOW(), NOW()),
(532, 'Toys & Games > Remote Control Cars', NOW(), NOW()),
(533, 'General & Misc > flowers', NOW(), NOW()),
(534, 'General & Misc > Gift', NOW(), NOW()),
(535, 'Computer & Software > PDAs > Palm OS > ACER S10', NOW(), NOW()),
(537, 'Jewellery & Accessories > Gemstones > Rings', NOW(), NOW()),
(538, 'Jewellery & Accessories > Diamond > Bracelets', NOW(), NOW()),
(539, 'Jewellery & Accessories > Diamond > Rings', NOW(), NOW()),
(540, 'Jewellery & Accessories > Diamond > Necklace', NOW(), NOW()),
(541, 'Jewellery & Accessories > Diamond > Other accesories', NOW(), NOW()),
(542, 'Jewellery & Accessories > Gemstones > Other accesories', NOW(), NOW()),
(543, 'Jewellery & Accessories > Gemstones > Necklace', NOW(), NOW()),
(544, 'Jewellery & Accessories > Gemstones > Bracelets', NOW(), NOW()),
(545, 'Electronics & Appliances > Home & Kitchen > Sewing machine', NOW(), NOW()),
(546, 'General & Misc > Education > Music & Dancing Lessons', NOW(), NOW()),
(547, 'General & Misc > Education > Others', NOW(), NOW()),
(548, 'Computer & Software > Hardware > Casing', NOW(), NOW()),
(549, 'Arts, Antiques & Collectibles > Stamps > Art Covers', NOW(), NOW()),
(550, 'Computer & Software > PDAs > General', NOW(), NOW()),
(551, 'Computer & Software > PDAs > Palm OS > Palm M125', NOW(), NOW()),
(552, 'Sports & Recreation > Tools', NOW(), NOW()),
(553, 'Computer & Software > Hardware > UPS & AVR', NOW(), NOW()),
(555, 'Services > Videoman', NOW(), NOW()),
(556, 'Computer & Software > PDAs > Palm OS > Palm IIIx', NOW(), NOW()),
(557, 'Music & Song > Instrument > Electronic Keyboard', NOW(), NOW()),
(558, 'Computer & Software > PDAs > Palm OS > Palm 515', NOW(), NOW()),
(559, 'Computer & Software > PDAs > Palm OS > PALM i705', NOW(), NOW()),
(560, 'Computer & Software > Hardware > Memory > DDR RAM', NOW(), NOW()),
(562, 'Electronics & Appliances > Karaoke System', NOW(), NOW()),
(563, 'Electronics & Appliances > VCD & DVD Recorder', NOW(), NOW()),
(564, 'Computer & Software > Hardware > Drive > DVD Writer', NOW(), NOW()),
(565, 'Computer & Software > Computer Storage > Flash Memory', NOW(), NOW()),
(566, 'Computer & Software > Computer Storage > USB Pen / Thumb Drive', NOW(), NOW()),
(567, 'Cars & Transport > Cars > Ford', NOW(), NOW()),
(568, 'Cars & Transport > Cars > Proton', NOW(), NOW()),
(569, 'Cars & Transport > Cars > Toyota', NOW(), NOW()),
(570, 'Cars & Transport > Cars > Perodua', NOW(), NOW()),
(571, 'Cars & Transport > Cars > BMW', NOW(), NOW()),
(572, 'Cars & Transport > Cars > Nissan', NOW(), NOW()),
(573, 'Cars & Transport > Cars > Mazda', NOW(), NOW()),
(574, 'Cars & Transport > Cars > Volvo', NOW(), NOW()),
(575, 'Cars & Transport > Cars > Mercedes', NOW(), NOW()),
(576, 'Cars & Transport > Cars > Audi', NOW(), NOW()),
(577, 'Cars & Transport > Cars > Alfa Romeo', NOW(), NOW()),
(578, 'Cars & Transport > Cars > Honda', NOW(), NOW()),
(579, 'Cars & Transport > Cars > Hyundai', NOW(), NOW()),
(581, 'Cars & Transport > Cars > Daihatsu', NOW(), NOW()),
(582, 'Cars & Transport > Cars > Kia', NOW(), NOW()),
(583, 'Cars & Transport > Cars > Renault', NOW(), NOW()),
(584, 'Cars & Transport > Cars > Fiat', NOW(), NOW()),
(585, 'Cars & Transport > Cars > Citreon', NOW(), NOW()),
(586, 'Cars & Transport > Cars > Isuzu', NOW(), NOW()),
(587, 'Cars & Transport > Cars > Opel', NOW(), NOW()),
(588, 'Cars & Transport > Cars > Peugeot', NOW(), NOW()),
(589, 'Cars & Transport > Cars > Austin', NOW(), NOW()),
(591, 'Cars & Transport > Cars > Mitsubishi', NOW(), NOW()),
(592, 'Cars & Transport > Cars > Others', NOW(), NOW()),
(593, 'Cars & Transport > Cars > Volkswagon', NOW(), NOW()),
(594, 'Cars & Transport > Cars > Saab', NOW(), NOW()),
(595, 'Cars & Transport > Cars > Rover', NOW(), NOW()),
(596, 'Cars & Transport > Cars > Porsche', NOW(), NOW()),
(597, 'Cars & Transport > Cars > Ferrari', NOW(), NOW()),
(598, 'Cars & Transport > Cars > Suzuki', NOW(), NOW()),
(599, 'Cars & Transport > Cars > Subaru', NOW(), NOW()),
(600, 'Cars & Transport > Cars > Rolls-Royce', NOW(), NOW()),
(601, 'Electronics & Appliances > Home & Kitchen > Toasters & Sandwich Maker', NOW(), NOW()),
(602, 'Computer & Software > PDAs > Palm OS > PALM Tungsten T', NOW(), NOW()),
(604, 'Cars & Transport > Car Magazine & Books', NOW(), NOW()),
(605, 'Cars & Transport > Others', NOW(), NOW()),
(606, 'Computer & Software > Hardware > Printer > Toner Refurbish', NOW(), NOW()),
(607, 'Computer & Software > Hardware > Printer > Toner Refill', NOW(), NOW()),
(608, 'Services > Credit Card Application', NOW(), NOW()),
(609, 'Services > Fortune Telling', NOW(), NOW()),
(610, 'Computer & Software > Hardware > Printer > Plotter and Line Printer', NOW(), NOW()),
(612, 'Computer & Software > Refurbished > PC & Server', NOW(), NOW()),
(613, 'Computer & Software > Refurbished > Notebook', NOW(), NOW()),
(614, 'Sports & Recreation > Archery', NOW(), NOW()),
(615, 'Travel, Tours & Hotel > Time Sharing', NOW(), NOW()),
(616, 'Computer & Software > Game > Prepaid Card', NOW(), NOW()),
(617, 'Toys & Games > Soft Toy', NOW(), NOW()),
(618, 'Computer & Software > Hardware > Printer > Color Laserjet Printer', NOW(), NOW()),
(619, 'Electronics & Appliances > Cable', NOW(), NOW()),
(620, 'Toys & Games > Board Games', NOW(), NOW()),
(621, 'Computer & Software > Hardware > Printer > Original Toner Cartridge', NOW(), NOW()),
(622, 'Cars & Transport > Parts & Accessories > Air Filter', NOW(), NOW()),
(623, 'Beauty & Personal Care > Hair Care', NOW(), NOW()),
(626, 'Arts, Antiques & Collectibles > Others', NOW(), NOW()),
(627, 'Arts, Antiques & Collectibles > Brand Tag', NOW(), NOW()),
(632, 'Services > Private Investigation Services', NOW(), NOW()),
(633, 'Electronics & Appliances > Auto Gate System', NOW(), NOW()),
(634, 'Electronics & Appliances > Home & Kitchen > Cooker Hood', NOW(), NOW()),
(635, 'Toys & Games > Model Kit', NOW(), NOW()),
(636, 'Beauty & Personal Care > Health & Wellness > Relaxation Device', NOW(), NOW()),
(637, 'Toys & Games > Educational', NOW(), NOW()),
(638, 'Beauty & Personal Care > Eye Care', NOW(), NOW()),
(640, 'Electronics & Appliances > Fire Alarm Products', NOW(), NOW()),
(642, 'Ticket > Concert Ticket', NOW(), NOW()),
(643, 'Ticket > Air Ticket', NOW(), NOW()),
(644, 'Ticket > Bus Ticket', NOW(), NOW()),
(645, 'Ticket > Train Ticket', NOW(), NOW()),
(646, 'Ticket > Any Other Ticket', NOW(), NOW()),
(647, 'Ticket > Opera Ticket', NOW(), NOW()),
(648, 'Electronics & Appliances > Audio > Walkman', NOW(), NOW()),
(649, 'Computer & Software > Hardware > Sound Card', NOW(), NOW()),
(650, 'Books & Comics > Misc', NOW(), NOW()),
(654, 'Services > Others > Administrative', NOW(), NOW()),
(655, 'Computer & Software > WIFI / WLAN', NOW(), NOW()),
(656, 'General & Misc > Education > Higher Education', NOW(), NOW()),
(658, 'Computer & Software > Computer Storage > 3.5\" Hard Disk Enclosure', NOW(), NOW()),
(659, 'Computer & Software > Computer Storage > Card Reader', NOW(), NOW()),
(660, 'Computer & Software > Computer Storage > 2.5\" Hard Disk Enclosure', NOW(), NOW()),
(661, 'Computer & Software > TV / Video Card', NOW(), NOW()),
(666, 'Computer & Software > Software > PC > Education', NOW(), NOW()),
(667, 'Computer & Software > Software > PC > Utility & System Tools', NOW(), NOW()),
(668, 'Computer & Software > Computer Storage > 5.25\" CD/DVD External Case', NOW(), NOW()),
(669, 'Music & Song > Instrument > Clarinet', NOW(), NOW()),
(671, 'Services > Photography Services', NOW(), NOW()),
(672, 'Computer & Software > Hardware > USB Card', NOW(), NOW()),
(673, 'Computer & Software > Hardware > CPU > CPU Accessories', NOW(), NOW()),
(674, 'Toys & Games > Game Console > Microsoft XBOX', NOW(), NOW()),
(675, 'House & Property > Town House', NOW(), NOW()),
(676, 'House & Property > Villa', NOW(), NOW()),
(677, 'Electronics & Appliances > Home & Kitchen > Water Dispenser', NOW(), NOW()),
(679, 'Home & Gardening > DIY Tools', NOW(), NOW()),
(680, 'Computer & Software > Cooling Component & Accessories', NOW(), NOW()),
(681, 'Computer & Software > Cutting Plotter', NOW(), NOW()),
(682, 'Computer & Software > Hardware > Input Devices > Mouse Pad', NOW(), NOW()),
(683, 'Books & Comics > Dictionary', NOW(), NOW()),
(684, 'Arts, Antiques & Collectibles > Fossils', NOW(), NOW()),
(685, 'Fashion > Women > Clothing > Jeans', NOW(), NOW()),
(686, 'B2B & Industrial Products > Recycle Goods & Assets', NOW(), NOW()),
(687, 'B2B & Industrial Products > Business Opportunities', NOW(), NOW()),
(694, 'Phone & Tablet > Accessories > Charger', NOW(), NOW()),
(695, 'Phone & Tablet > Accessories > Batteries', NOW(), NOW()),
(696, 'Phone & Tablet > Accessories > Others', NOW(), NOW()),
(697, 'Phone & Tablet > Accessories > Bags & Case', NOW(), NOW()),
(699, 'Phone & Tablet > Accessories > Hand Free & Ear Phone', NOW(), NOW()),
(700, 'Phone & Tablet > Accessories > Bluetooth Ear Phone', NOW(), NOW()),
(702, 'Phone & Tablet > Services > Training & Courses', NOW(), NOW()),
(703, 'Phone & Tablet > Services > Rental', NOW(), NOW()),
(704, 'Phone & Tablet > Accessories > Data Cable', NOW(), NOW()),
(705, 'Phone & Tablet > Accessories > Sim Card & Kits', NOW(), NOW()),
(706, 'Phone & Tablet > Handphone > Nokia', NOW(), NOW()),
(707, 'Phone & Tablet > Handphone > Motorola', NOW(), NOW()),
(708, 'Phone & Tablet > Handphone > Sony Ericsson', NOW(), NOW()),
(709, 'Phone & Tablet > Handphone > Samsung', NOW(), NOW()),
(711, 'Phone & Tablet > Handphone > Panasonic', NOW(), NOW()),
(712, 'Phone & Tablet > Handphone > Alcatel', NOW(), NOW()),
(713, 'Phone & Tablet > Handphone > Sagem', NOW(), NOW()),
(714, 'Phone & Tablet > Handphone > LG', NOW(), NOW()),
(716, 'Phone & Tablet > Handphone > Others', NOW(), NOW()),
(720, 'Phone & Tablet > Handphone > Philips', NOW(), NOW()),
(725, 'Computer & Software > Hard Disk > SCSI Hard Disk', NOW(), NOW()),
(726, 'Computer & Software > Hard Disk > Notebook Hard Disk', NOW(), NOW()),
(727, 'Computer & Software > Computer Storage > DVD Rom', NOW(), NOW()),
(728, 'Computer & Software > Computer Storage > DVD RW', NOW(), NOW()),
(729, 'Computer & Software > Bluetooth', NOW(), NOW()),
(730, 'Toys & Games > Magic Supplies', NOW(), NOW()),
(731, 'Toys & Games > Others', NOW(), NOW()),
(732, 'Home & Gardening > Mug', NOW(), NOW()),
(733, 'Home & Gardening > Photo Frame', NOW(), NOW()),
(734, 'Electronics & Appliances > Flashlight', NOW(), NOW()),
(735, 'Electronics & Appliances > GPS', NOW(), NOW()),
(739, 'Music & Song > Others', NOW(), NOW()),
(740, 'Music & Song > DVD', NOW(), NOW()),
(741, 'Services > Graphic Design', NOW(), NOW()),
(742, 'Services > Web Design', NOW(), NOW()),
(743, 'Services > Programming', NOW(), NOW()),
(744, 'Computer & Software > Hardware > Controller Card', NOW(), NOW()),
(745, 'Computer & Software > Hardware > Printer > Memory', NOW(), NOW()),
(746, 'Computer & Software > Hardware > Printer > Others', NOW(), NOW()),
(747, 'Computer & Software > Hardware > Barcode Scanner', NOW(), NOW()),
(748, 'Services > Copywriting & Translation', NOW(), NOW()),
(750, 'Sports & Recreation > Rock Climbing and Safety Equipments', NOW(), NOW()),
(751, 'Home & Gardening > Water Filter / Purifier', NOW(), NOW()),
(752, 'Music & Song > Instrument > Saxophone', NOW(), NOW()),
(753, 'Home & Gardening > Home Services > Home Cleaning', NOW(), NOW()),
(756, 'Books & Comics > Novel', NOW(), NOW()),
(757, 'Computer & Software > Hardware > CPU > Intel', NOW(), NOW()),
(758, 'Computer & Software > Hardware > CPU > AMD', NOW(), NOW()),
(759, 'Arts, Antiques & Collectibles > Cans & Bottles', NOW(), NOW()),
(760, 'Electronics & Appliances > Electronic Dictionary', NOW(), NOW()),
(762, 'Phone & Tablet > IDD Card & Airtime', NOW(), NOW()),
(764, 'Computer & Software > Notebook > Notebook', NOW(), NOW()),
(765, 'Computer & Software > Notebook > Accessories', NOW(), NOW()),
(766, 'Computer & Software > Notebook > Bag & Case', NOW(), NOW()),
(767, 'Computer & Software > Notebook > Battery', NOW(), NOW()),
(768, 'Electronics & Appliances > Portable AV', NOW(), NOW()),
(769, 'Computer & Software > Hardware > Mother Board > For Intel', NOW(), NOW()),
(770, 'Computer & Software > Hardware > Mother Board > For AMD', NOW(), NOW()),
(771, 'Computer & Software > Hardware > Mother Board > For Others', NOW(), NOW()),
(772, 'Electronics & Appliances > Home Theatre System', NOW(), NOW()),
(773, 'Arts, Antiques & Collectibles > Trading Cards > Yugioh Card', NOW(), NOW()),
(774, 'Computer & Software > PDAs > Palm OS > Palm Zire', NOW(), NOW()),
(775, 'Books & Comics > e-Book', NOW(), NOW()),
(776, 'Electronics & Appliances > Audio > Microcassette & Recorder', NOW(), NOW());";

$sql[] = "
INSERT INTO ".DB_PREFIX."lelong_category (`category_id`, `name`, `create_time`, `last_update`) VALUES
(777, 'Electronics & Appliances > Audio > Digital Voice Recorder', NOW(), NOW()),
(778, 'Home & Gardening > Kitchenware', NOW(), NOW()),
(779, 'Electronics & Appliances > Power Adapter', NOW(), NOW()),
(780, 'Computer & Software > PDAs > Palm OS > Palm Tungsten E', NOW(), NOW()),
(781, 'Services > Fortune Teller', NOW(), NOW()),
(782, 'Phone & Tablet > Accessories > Housing', NOW(), NOW()),
(783, 'Electronics & Appliances > Smart Home Equipment', NOW(), NOW()),
(786, 'Computer & Software > Hardware > Input Devices > Graphic Tablet', NOW(), NOW()),
(787, 'Computer & Software > Hardware > Printer > All In One Printer', NOW(), NOW()),
(788, 'B2B & Industrial Products > Paper', NOW(), NOW()),
(789, 'Electronics & Appliances > Energy Saver', NOW(), NOW()),
(790, 'Electronics & Appliances > Audio > HI FI Cables / Interconnects', NOW(), NOW()),
(792, 'Arts, Antiques & Collectibles > Postcard', NOW(), NOW()),
(793, 'Sports & Recreation > Football', NOW(), NOW()),
(794, 'Toys & Games > Game Console > Gamecube', NOW(), NOW()),
(795, 'Arts, Antiques & Collectibles > Stamps > China', NOW(), NOW()),
(796, 'Home & Gardening > Insect Repellent', NOW(), NOW()),
(797, 'Electronics & Appliances > Electrical & Electronics Service', NOW(), NOW()),
(798, 'Cars & Transport > Parts & Accessories > Fuel Catalyst', NOW(), NOW()),
(800, 'Computer & Software > Accessories > Surge Protector', NOW(), NOW()),
(801, 'Computer & Software > Accessories > CD Storage', NOW(), NOW()),
(802, 'Arts, Antiques & Collectibles > Phone Card', NOW(), NOW()),
(803, 'Music & Song > Instrument > Violin', NOW(), NOW()),
(804, 'Jewellery & Accessories > Gemstones > Genuine Loose Gemstones', NOW(), NOW()),
(805, 'Jewellery & Accessories > Gemstones > Created Loose Gemstones', NOW(), NOW()),
(806, 'Jewellery & Accessories > Gemstones > Other Gemstones items', NOW(), NOW()),
(807, 'Computer & Software > Hardware > Modem > ADSL', NOW(), NOW()),
(808, 'Services > Printing Services', NOW(), NOW()),
(809, 'Electronics & Appliances > Personal Protective Equipment', NOW(), NOW()),
(810, 'General & Misc > Personal Security', NOW(), NOW()),
(811, 'Beauty & Personal Care > Personal Care', NOW(), NOW()),
(812, 'Jewellery & Accessories > Swarovski Crystal', NOW(), NOW()),
(813, 'Computer & Software > PDAs > Palm OS > M130', NOW(), NOW()),
(814, 'Cars & Transport > Parts & Accessories > Air Ionizer / Cleaner', NOW(), NOW()),
(815, 'Home & Gardening > Air Cleaner / Refresher', NOW(), NOW()),
(816, 'Arts, Antiques & Collectibles > Badges', NOW(), NOW()),
(817, 'Books & Comics > Magazine > Others', NOW(), NOW()),
(818, 'Arts, Antiques & Collectibles > Thailand Buddhism & Amulet', NOW(), NOW()),
(820, 'Toys & Games > Remote Control Hellicopter', NOW(), NOW()),
(822, 'Special Interest', NOW(), NOW()),
(824, 'Home & Gardening > Curtains & Blinds > PVC', NOW(), NOW()),
(825, 'Home & Gardening > Curtains & Blinds > Bamboo', NOW(), NOW()),
(826, 'Home & Gardening > Curtains & Blinds > General', NOW(), NOW()),
(827, 'Ticket > F1 Tickets', NOW(), NOW()),
(828, 'Arts, Antiques & Collectibles > Brooch', NOW(), NOW()),
(829, 'Arts, Antiques & Collectibles > Watercolour', NOW(), NOW()),
(830, 'Toys & Games > Remote Control Plane', NOW(), NOW()),
(831, 'Books & Comics > Recipes', NOW(), NOW()),
(832, 'Toys & Games > Tanks', NOW(), NOW()),
(834, 'Arts, Antiques & Collectibles > Painting', NOW(), NOW()),
(837, 'Internet > Web Hosting', NOW(), NOW()),
(838, 'Internet > Web Design', NOW(), NOW()),
(839, 'Internet > Web Template', NOW(), NOW()),
(841, 'Internet > Broadband > Streamyx', NOW(), NOW()),
(842, 'Internet > Broadband > Jaring', NOW(), NOW()),
(843, 'Internet > Broadband > Maxis', NOW(), NOW()),
(844, 'Internet > Broadband > Others', NOW(), NOW()),
(845, 'Internet > Software & Application', NOW(), NOW()),
(846, 'Internet > Others', NOW(), NOW()),
(847, 'Toys & Games > Poker Cards', NOW(), NOW()),
(848, 'Computer & Software > Server Rack', NOW(), NOW()),
(849, 'Electronics & Appliances > Measuring Equipment', NOW(), NOW()),
(850, 'Books & Comics > Fiction > Thriller/Horror', NOW(), NOW()),
(851, 'Books & Comics > Fiction > Criminal', NOW(), NOW()),
(852, 'B2B & Industrial Products > Office Furniture', NOW(), NOW()),
(853, 'Rental, To Let & For Hire > Office Space / Lot', NOW(), NOW()),
(854, 'Books & Comics > Fiction > Contemporary', NOW(), NOW()),
(855, 'Cars & Transport > Car Alarm System', NOW(), NOW()),
(856, 'Fashion > Women > Clothing > Dresses', NOW(), NOW()),
(857, 'Books & Comics > Finance & Investment', NOW(), NOW()),
(858, 'Books & Comics > Law', NOW(), NOW()),
(859, 'Books & Comics > Programming', NOW(), NOW()),
(860, 'Books & Comics > Graphic & Design', NOW(), NOW()),
(862, 'Beauty & Personal Care > Kids', NOW(), NOW()),
(863, 'Books & Comics > Historical', NOW(), NOW()),
(864, 'Toys & Games > Mini Figures', NOW(), NOW()),
(865, 'Gifts & Premiums > Gifts & Premiums', NOW(), NOW()),
(866, 'Gifts & Premiums > Flowers', NOW(), NOW()),
(867, 'Electronics & Appliances > Office Automation', NOW(), NOW()),
(868, 'Computer & Software > Computer Storage > DVD Media', NOW(), NOW()),
(869, 'Food & Beverages > Food', NOW(), NOW()),
(871, 'Home & Gardening > Food & Beverage Container', NOW(), NOW()),
(874, 'Rental, To Let & For Hire > Notebook & Computer', NOW(), NOW()),
(875, 'Rental, To Let & For Hire > Projector', NOW(), NOW()),
(876, 'Sports & Recreation > Equipment', NOW(), NOW()),
(878, 'Phone & Tablet > Accessories > Spare Parts', NOW(), NOW()),
(879, 'Cars & Transport > Car Sport Steering', NOW(), NOW()),
(880, 'Books & Comics > Health,Mind & Body', NOW(), NOW()),
(881, 'Books & Comics > Animal', NOW(), NOW()),
(882, 'Toys & Games > Remote Control Toys', NOW(), NOW()),
(883, 'Books & Comics > Plants', NOW(), NOW()),
(886, 'Office Equipment > Stationeries', NOW(), NOW()),
(887, 'Office Equipment > Writting Instruments', NOW(), NOW()),
(888, 'Office Equipment > Paper', NOW(), NOW()),
(889, 'Office Equipment > Others', NOW(), NOW()),
(890, 'Beauty & Personal Care > Spa Treatment', NOW(), NOW()),
(891, 'Fashion > Women > Accessories > Fascinators & Hair Accessories', NOW(), NOW()),
(892, 'Books & Comics > Mother & Baby', NOW(), NOW()),
(893, 'Books & Comics > Classic', NOW(), NOW()),
(894, 'Books & Comics > Western', NOW(), NOW()),
(895, 'Cars & Transport > Motorcycles > Motorcycles', NOW(), NOW()),
(896, 'Cars & Transport > Motorcycles > Accessories', NOW(), NOW()),
(897, 'Cars & Transport > Motorcycles > Alarm System', NOW(), NOW()),
(898, 'Sports & Recreation > Backpack and Bags', NOW(), NOW()),
(899, 'Home & Gardening > Table Ware', NOW(), NOW()),
(900, 'Books & Comics > War & Military', NOW(), NOW()),
(901, 'Books & Comics > Children > Mysteries & Detective', NOW(), NOW()),
(902, 'Books & Comics > Children > Children & Teen', NOW(), NOW()),
(903, 'Arts, Antiques & Collectibles > Fridge Magnets', NOW(), NOW()),
(904, 'Fashion > Men > Accessories > Ties, Bow Ties & Tie Clips', NOW(), NOW()),
(905, 'Phone & Tablet > Handphone > O2', NOW(), NOW()),
(906, 'Arts, Antiques & Collectibles > Trading Cards > Others', NOW(), NOW()),
(907, 'Arts, Antiques & Collectibles > Trading Cards > Magic the Gathering', NOW(), NOW()),
(908, 'Home & Gardening > Cooking Class', NOW(), NOW()),
(909, 'Books & Comics > Psychology', NOW(), NOW()),
(910, 'Books & Comics > Political', NOW(), NOW()),
(914, 'Fashion > Women > Accessories > Belt & Belt Buckles', NOW(), NOW()),
(916, 'Fashion > Women > Clothing > Legging & Jegging', NOW(), NOW()),
(918, 'Fashion > Women > Clothing > Skirts', NOW(), NOW()),
(919, 'Fashion > Women > Clothing > Shirt & Blouses', NOW(), NOW()),
(920, 'Fashion > Women > Clothing > Pants & Caprits', NOW(), NOW()),
(924, 'Food & Beverages > Spices', NOW(), NOW()),
(925, 'Books & Comics > Almanac', NOW(), NOW()),
(928, 'Computer & Software > Hardware > Monitors >  TFT Monitor', NOW(), NOW()),
(929, 'Computer & Software > Hardware > Monitors > LCD Monitor', NOW(), NOW()),
(933, 'Warehouse Sales !! > Penang', NOW(), NOW()),
(934, 'Warehouse Sales !! > Johor', NOW(), NOW()),
(935, 'Warehouse Sales !! > Selangor > Subang', NOW(), NOW()),
(936, 'Warehouse Sales !! > Selangor > Petaling Jaya', NOW(), NOW()),
(939, 'Warehouse Sales !! > Selangor > Klang', NOW(), NOW()),
(940, 'Warehouse Sales !! > Selangor > Shah Alam', NOW(), NOW()),
(941, 'Warehouse Sales !! > Kuala Lumpur > Ampang', NOW(), NOW()),
(942, 'Warehouse Sales !! > Kuala Lumpur > Cheras', NOW(), NOW()),
(943, 'Warehouse Sales !! > Kuala Lumpur > Others', NOW(), NOW()),
(944, 'Warehouse Sales !! > Selangor > Others', NOW(), NOW()),
(947, 'Computer & Software > Hardware > Memory > DDR2 RAM', NOW(), NOW()),
(948, 'Home & Gardening > Storage Rack', NOW(), NOW()),
(950, 'Home & Gardening > Gardening > Garden Shed', NOW(), NOW()),
(951, 'Phone & Tablet > Voip Phone', NOW(), NOW()),
(952, 'Books & Comics > Autobiography', NOW(), NOW()),
(953, 'Beauty & Personal Care > Perfumes > For All', NOW(), NOW()),
(954, 'Books & Comics > Fiction > Fantasy', NOW(), NOW()),
(955, 'Jewellery & Accessories > Diamond > Pendant', NOW(), NOW()),
(956, 'Jewellery & Accessories > Gemstones > Pendant', NOW(), NOW()),
(957, 'Jewellery & Accessories > Pendant', NOW(), NOW()),
(959, 'Cars & Transport > Bicycle > Mountain Bike', NOW(), NOW()),
(960, 'Travel, Tours & Hotel > Map', NOW(), NOW()),
(961, 'Jewellery & Accessories > Jewellery Case', NOW(), NOW()),
(962, 'Cars & Transport > Oil & Lubricant > Oil & Lubricant', NOW(), NOW()),
(964, 'Cars & Transport > Oil & Lubricant > Additive', NOW(), NOW()),
(966, 'Books & Comics > Art > Art', NOW(), NOW()),
(967, 'Books & Comics > Art > Metal/Iron Art', NOW(), NOW()),
(968, 'Books & Comics > Art > Wood Art', NOW(), NOW()),
(970, 'Sports & Recreation > Diving > Equipment', NOW(), NOW()),
(971, 'Sports & Recreation > Diving > Scuba Diving', NOW(), NOW()),
(972, 'Sports & Recreation > Diving > Courses', NOW(), NOW()),
(973, 'Ticket > Movie Ticket', NOW(), NOW()),
(977, 'Home & Gardening > Salt Lamp', NOW(), NOW()),
(978, 'Books & Comics > Humour', NOW(), NOW()),
(981, 'Watches & Clocks > Watches > Original', NOW(), NOW()),
(982, 'Watches & Clocks > Watches > Others', NOW(), NOW()),
(983, 'Watches & Clocks > Pens', NOW(), NOW()),
(984, 'Watches & Clocks > Clocks', NOW(), NOW()),
(985, 'Computer & Software > Computer Storage > 1.8\" Hard Disk Enclosure', NOW(), NOW()),
(986, 'Computer & Software > Computer Storage > 1\" Hard Disk Enclosure', NOW(), NOW()),
(989, 'Services > Lelong Outsourcing > Posting & Selling', NOW(), NOW()),
(992, 'Cars & Transport > Transport & Mover Services', NOW(), NOW()),
(993, 'Services > Financial Planning', NOW(), NOW()),
(995, 'Sports & Recreation > Sports Nutrition', NOW(), NOW()),
(996, 'Arts, Antiques & Collectibles > Matches Boxes', NOW(), NOW()),
(997, 'Arts, Antiques & Collectibles > Rocks & Stones', NOW(), NOW()),
(998, 'Pet Supplies > Aquarium & Fish', NOW(), NOW()),
(999, 'Arts, Antiques & Collectibles > Stickers', NOW(), NOW()),
(1000, 'Cars & Transport > Car Stickers', NOW(), NOW()),
(1001, 'Internet > Auction Template', NOW(), NOW()),
(1002, 'Internet > Auction Posting Services', NOW(), NOW()),
(1003, 'Computer & Software > PDAs > Palm OS > Lifedrive', NOW(), NOW()),
(1005, 'Electronics & Appliances > Generator', NOW(), NOW()),
(1007, 'Computer & Software > Hardware > Switch & Router > Wired', NOW(), NOW()),
(1008, 'Computer & Software > Hardware > Switch & Router > Wireless', NOW(), NOW()),
(1009, 'Toys & Games > Game Console > Sony > PSP', NOW(), NOW()),
(1010, 'Food & Beverages > Tea', NOW(), NOW()),
(1011, 'Arts, Antiques & Collectibles > Brass & Bronze', NOW(), NOW()),
(1012, 'Warehouse Sales !! > Others', NOW(), NOW()),
(1013, 'Cars & Transport > Windscreen', NOW(), NOW()),
(1014, 'Cars & Transport > Cars > Chevrolet', NOW(), NOW()),
(1017, 'Jobs & Freelances > Information Technology', NOW(), NOW()),
(1018, 'Jobs & Freelances > Others', NOW(), NOW()),
(1019, 'Computer & Software > Hardware > Printer > Barcode Printer', NOW(), NOW()),
(1020, 'Computer & Software > Hardware > Pos Hardware', NOW(), NOW()),
(1021, 'Computer & Software > Hardware > Printer > Receipt Printer', NOW(), NOW()),
(1022, 'Beauty & Personal Care > Bird Nest', NOW(), NOW()),
(1025, 'Books & Comics > Games & Sports', NOW(), NOW()),
(1026, 'Cars & Transport > Motorcycles > Helmet', NOW(), NOW()),
(1027, 'Sports & Recreation > PaintBall', NOW(), NOW()),
(1028, 'Electronics & Appliances > Battery', NOW(), NOW()),
(1029, 'Beauty & Personal Care > Nail Care', NOW(), NOW()),
(1030, 'Computer & Software > Hardware > Monitors > LCD TV', NOW(), NOW()),
(1031, 'Sports & Recreation > Basket Ball', NOW(), NOW()),
(1032, 'Food & Beverages > Frozen Food', NOW(), NOW()),
(1033, 'B2B & Industrial Products > Material Handling', NOW(), NOW()),
(1035, 'Electronics & Appliances > Multimedia & HDD Player', NOW(), NOW()),
(1036, 'Travel, Tours & Hotel > Travel & Vacation > Management Services', NOW(), NOW()),
(1037, 'Jewellery & Accessories > Bangle', NOW(), NOW()),
(1038, 'Services > Business Plan Writting', NOW(), NOW()),
(1039, 'Feng Shui', NOW(), NOW()),
(1040, 'Books & Comics > Encylopedia', NOW(), NOW()),
(1041, 'Phone & Tablet > Handphone > Dopod', NOW(), NOW()),
(1042, 'Computer & Software > Furniture', NOW(), NOW()),
(1043, 'Services > Videography Services', NOW(), NOW()),
(1044, 'Computer & Software > Hardware > Monitors > Touch Screen', NOW(), NOW()),
(1045, 'Food & Beverages > Honey / Wild Honey', NOW(), NOW()),
(1046, 'Sports & Recreation > Fishing > Others', NOW(), NOW()),
(1047, 'Toys & Games > Puzzles', NOW(), NOW()),
(1048, 'Books & Comics > Reader Digest', NOW(), NOW()),
(1049, 'Jobs & Freelances > Jobs', NOW(), NOW()),
(1050, 'Arts, Antiques & Collectibles > Paper Bag', NOW(), NOW()),
(1051, 'Home & Gardening > Bedding', NOW(), NOW()),
(1052, 'Services > Company Registration', NOW(), NOW()),
(1054, 'Pet Supplies > Food', NOW(), NOW()),
(1055, 'Pet Supplies > Pet Adoption', NOW(), NOW()),
(1056, 'Food & Beverages > Supplementary Food', NOW(), NOW()),
(1057, 'Sports & Recreation > Rugby', NOW(), NOW()),
(1058, 'Electronics & Appliances > Air-Conditioning', NOW(), NOW()),
(1060, 'Cars & Transport > Cars > Naza', NOW(), NOW()),
(1061, 'Cars & Transport > Cars > SsangYong', NOW(), NOW()),
(1062, 'Electronics & Appliances > Massage Equipment', NOW(), NOW()),
(1064, 'Fashion > Men > Clothing > Underwear', NOW(), NOW()),
(1065, 'Cars & Transport > Parts & Accessories > Racing Equipment', NOW(), NOW()),
(1066, 'Cars & Transport > Parts & Accessories > Performance Improvement', NOW(), NOW()),
(1067, 'Food & Beverages > Candy', NOW(), NOW()),
(1068, 'Food & Beverages > Chocolate', NOW(), NOW()),
(1069, 'Fashion > Women > Clothing > Swim Wear', NOW(), NOW()),
(1070, 'Jewellery & Accessories > Brooch', NOW(), NOW()),
(1071, 'Jewellery & Accessories > Body Jewellery', NOW(), NOW()),
(1072, 'Toys & Games > Online Games', NOW(), NOW()),
(1073, 'Sports & Recreation > Ice Skating', NOW(), NOW()),
(1074, 'Phone & Tablet > Repair Services', NOW(), NOW()),
(1075, 'Sports & Recreation > Sport Collectibles', NOW(), NOW()),
(1077, 'Jewellery & Accessories > Anklets', NOW(), NOW()),
(1079, 'Jewellery & Accessories > Jade', NOW(), NOW()),
(1080, 'Music & Song > DJ Instruments', NOW(), NOW()),
(1081, 'Home & Gardening > Gate & Window', NOW(), NOW()),
(1083, 'Food & Beverages > MoonCake > Traditional', NOW(), NOW()),
(1084, 'Food & Beverages > MoonCake > Ice-skin', NOW(), NOW()),
(1085, 'Food & Beverages > MoonCake > Shanghai', NOW(), NOW()),
(1086, 'Food & Beverages > MoonCake > Special !', NOW(), NOW()),
(1087, 'Food & Beverages > MoonCake > Others', NOW(), NOW()),
(1088, 'Sports & Recreation > Martial Art', NOW(), NOW()),
(1090, 'Jewellery & Accessories > Findings & Parts', NOW(), NOW()),
(1091, 'Books & Comics > Guide Book', NOW(), NOW()),
(1092, 'Toys & Games > Robot', NOW(), NOW()),
(1093, 'Food & Beverages > Kuih Raya', NOW(), NOW()),
(1094, 'Arts, Antiques & Collectibles > Sports / Racket', NOW(), NOW()),
(1095, 'Office Equipment > Rubber Stamp', NOW(), NOW()),
(1096, 'Pet Supplies > Pets Accessories', NOW(), NOW()),
(1097, 'Cars & Transport > Parts & Accessories > Canopy', NOW(), NOW()),
(1098, 'Computer & Software > Hardware > PC Card', NOW(), NOW()),
(1099, 'Jewellery & Accessories > Rings', NOW(), NOW()),
(1101, 'Fashion > Women > Intimate & Sleep > Panties', NOW(), NOW()),
(1102, 'Fashion > Women > Intimate & Sleep > Sleepwear & Robes', NOW(), NOW()),
(1104, 'Fashion > Women > Intimate & Sleep > Corsets & Bustiers', NOW(), NOW()),
(1105, 'Fashion > Men > Shoes > Casual', NOW(), NOW()),
(1106, 'Fashion > Women > Shoes > Heels', NOW(), NOW()),
(1107, 'Fashion > Women > Shoes > Sandals & Flip Flops', NOW(), NOW()),
(1108, 'Fashion > Women > Shoes > Boots', NOW(), NOW()),
(1109, 'Fashion > Men > Shoes > Sports', NOW(), NOW()),
(1110, 'Toys & Games > Model > Building', NOW(), NOW()),
(1111, 'Toys & Games > Model > Military Figure', NOW(), NOW()),
(1112, 'Pet Supplies > Arowana', NOW(), NOW()),
(1113, 'Office Equipment > Water Dispenser', NOW(), NOW()),
(1114, 'Toys & Games > Funny & Weird Toys', NOW(), NOW()),
(1115, 'Gifts & Premiums > Key Chain', NOW(), NOW()),
(1116, 'Food & Beverages > Abalone', NOW(), NOW()),
(1117, 'Books & Comics > Diary', NOW(), NOW()),
(1118, 'Services > Translation', NOW(), NOW()),
(1119, 'Cars & Transport > Car Care', NOW(), NOW()),
(1120, 'Services > Training', NOW(), NOW()),
(1121, 'Fashion > Women > Accessories > Scarf & Shawls', NOW(), NOW()),
(1122, 'Computer & Software > PDAs > Palm OS > Palm Treo', NOW(), NOW()),
(1123, 'Home & Gardening > Light & Lighting', NOW(), NOW()),
(1124, 'Books & Comics > Drama', NOW(), NOW()),
(1125, 'Books & Comics > Social Sciences', NOW(), NOW()),
(1126, 'Books & Comics > Non Fiction', NOW(), NOW()),
(1127, 'Electronics & Appliances > Home & Kitchen > Oven', NOW(), NOW()),
(1129, 'Health & Medical > Herbs', NOW(), NOW()),
(1130, 'Health & Medical > Supplements & Nutrition', NOW(), NOW()),
(1131, 'Health & Medical > Slimming', NOW(), NOW()),
(1132, 'Health & Medical > Relaxation Devices', NOW(), NOW()),
(1133, 'Health & Medical > Equipment & Aids', NOW(), NOW()),
(1134, 'Health & Medical > Aromatheraphy', NOW(), NOW()),
(1135, 'Health & Medical > Massage', NOW(), NOW()),
(1136, 'Health & Medical > Education & Courses', NOW(), NOW()),
(1137, 'Health & Medical > Programmes', NOW(), NOW()),
(1138, 'Health & Medical > Others', NOW(), NOW()),
(1139, 'Beauty & Personal Care > Oral & Lips Care', NOW(), NOW()),
(1140, 'Beauty & Personal Care > Bath & Body', NOW(), NOW()),
(1141, 'Beauty & Personal Care > Make-up Tools', NOW(), NOW()),
(1142, 'Toys & Games > Game Console > Sony > Playstation 3', NOW(), NOW()),
(1143, 'Books & Comics > Religion', NOW(), NOW()),
(1144, 'Health & Medical > Consumables', NOW(), NOW()),
(1145, 'Health & Medical > Bird Nest', NOW(), NOW()),
(1147, 'Camera & Camcorder > Film Cameras', NOW(), NOW()),
(1149, 'Camera & Camcorder > Digital Cameras > Point & Shoot', NOW(), NOW()),
(1150, 'Camera & Camcorder > Digital Cameras > Digital SLR', NOW(), NOW()),
(1151, 'Camera & Camcorder > Lenses & Filters', NOW(), NOW()),
(1152, 'Camera & Camcorder > Lighting & Studio Equipment', NOW(), NOW()),
(1153, 'Camera & Camcorder > Accessories', NOW(), NOW()),
(1154, 'Camera & Camcorder > Vintage & Collectible', NOW(), NOW()),
(1155, 'Camera & Camcorder > Bags, Cases & Straps', NOW(), NOW()),
(1156, 'Camera & Camcorder > Camcorders', NOW(), NOW()),
(1157, 'Camera & Camcorder > Photo Album', NOW(), NOW()),
(1158, 'Camera & Camcorder > Flashes', NOW(), NOW()),
(1159, 'Camera & Camcorder > Tripods', NOW(), NOW()),
(1160, 'Camera & Camcorder > General', NOW(), NOW()),
(1161, 'Camera & Camcorder > Binoculars & Telescopes', NOW(), NOW()),
(1162, 'Camera & Camcorder > Darkroom Equipment', NOW(), NOW()),
(1163, 'Camera & Camcorder > Polaroid', NOW(), NOW()),
(1164, 'Camera & Camcorder > Camcorder Equipment', NOW(), NOW()),
(1165, 'Camera & Camcorder > Photo Printer', NOW(), NOW()),
(1166, 'Camera & Camcorder > Battery', NOW(), NOW()),
(1168, 'Computer & Software > Notebook > Spare Parts', NOW(), NOW()),
(1169, 'Sports & Recreation > Scuba Diving > Diving Equipment', NOW(), NOW()),
(1171, 'Electronics & Appliances > TV > LCD TV', NOW(), NOW()),
(1172, 'Electronics & Appliances > TV > Plasma TV', NOW(), NOW()),
(1173, 'Electronics & Appliances > TV > TV Antenna', NOW(), NOW()),
(1174, 'Phone & Tablet > Handphone > Palm Treo', NOW(), NOW()),
(1175, 'Computer & Software > PDAs > Battery', NOW(), NOW()),
(1176, 'Gifts & Premiums > Photo Frame', NOW(), NOW()),
(1177, 'Toys & Games > Toys', NOW(), NOW()),
(1178, 'Services > Payment Solution', NOW(), NOW()),
(1179, 'Toys & Games > Wooden Toys', NOW(), NOW()),
(1181, 'Phone & Tablet > Handphone > Asus', NOW(), NOW()),
(1182, 'Home & Gardening > Curtains & Blinds > Curtains', NOW(), NOW()),
(1183, 'Electronics & Appliances > Electronic Engineering', NOW(), NOW()),
(1184, 'Beauty & Personal Care > Shaver', NOW(), NOW()),
(1185, 'Electronics & Appliances > Home & Kitchen > Halogen Cooker', NOW(), NOW()),
(1186, 'Fashion > Women > Intimate & Sleep > Camisoles & Camisoles Sets', NOW(), NOW()),
(1187, 'Fashion > Women > Intimate & Sleep > Garter Belts', NOW(), NOW()),
(1189, 'Fashion > Women > Intimate & Sleep > Mixed Items and Lots', NOW(), NOW()),
(1190, 'Fashion > Women > Intimate & Sleep > Teddies', NOW(), NOW()),
(1191, 'Toys & Games > Hobby Tools', NOW(), NOW()),
(1192, 'Phone & Tablet > Handphone > HTC', NOW(), NOW()),
(1193, 'Phone & Tablet > Handphone > i-Mobile', NOW(), NOW()),
(1194, 'Phone & Tablet > Handphone > Look Alike', NOW(), NOW()),
(1195, 'Cars & Transport > Car Loan', NOW(), NOW()),
(1196, 'Phone & Tablet > Handphone > Apple iPhone', NOW(), NOW()),
(1197, 'Jewellery & Accessories > Necklaces > Necklaces', NOW(), NOW()),
(1198, 'Jewellery & Accessories > Necklaces > Titanium', NOW(), NOW()),
(1200, 'Beauty & Personal Care > Services > Hair-Do', NOW(), NOW()),
(1201, 'Beauty & Personal Care > Services > Make-up', NOW(), NOW()),
(1202, 'Beauty & Personal Care > Services > Manicure & Pedicure', NOW(), NOW()),
(1203, 'Beauty & Personal Care > Services > Facial', NOW(), NOW()),
(1204, 'Home & Gardening > Timber Products', NOW(), NOW()),
(1206, 'Gifts & Premiums > Hampers', NOW(), NOW()),
(1207, 'Computer & Software > Notebook > Docking Station', NOW(), NOW()),
(1209, 'Fashion > Men > Accessories > Belt & Belt Buckles', NOW(), NOW()),
(1210, 'Phone & Tablet > Handphone > HP', NOW(), NOW()),
(1211, 'Home & Gardening > Hardware', NOW(), NOW()),
(1213, 'Cars & Transport > Cars > Mahindra', NOW(), NOW()),
(1215, 'Phone & Tablet > SMS > Services', NOW(), NOW()),
(1216, 'Food & Beverages > Cookies', NOW(), NOW()),
(1217, 'Food & Beverages > Cake', NOW(), NOW()),
(1218, 'Cars & Transport > In Car Entertainment > Amplifier', NOW(), NOW()),
(1219, 'Cars & Transport > In Car Entertainment > In Car Entertainment', NOW(), NOW()),
(1220, 'Electronics & Appliances > Security System > CCTV & Security Alarm', NOW(), NOW()),
(1221, 'Electronics & Appliances > Security System > Parts and Accessories', NOW(), NOW()),
(1222, 'Computer & Software > Hardware > Memory > DDR3 RAM', NOW(), NOW()),
(1223, 'B2B & Industrial Products > Stock & Shares', NOW(), NOW()),
(1224, 'Phone & Tablet > Handphone > TV Mobile Phone', NOW(), NOW()),
(1225, 'Books & Comics > Fiction > Spy', NOW(), NOW()),
(1226, 'Arts, Antiques & Collectibles > Stamps > Worldwide Mix', NOW(), NOW()),
(1227, 'Services > Renovation Work', NOW(), NOW()),
(1228, 'Services > Interior Design', NOW(), NOW()),
(1229, 'Gifts & Premiums > Wishing Card', NOW(), NOW()),
(1230, 'Home & Gardening > Solar Home Solutions', NOW(), NOW()),
(1231, 'Electronics & Appliances > Solar Products', NOW(), NOW()),
(1232, 'Phone & Tablet > Handphone > CSL', NOW(), NOW()),
(1235, 'Phone & Tablet > Prepaid Cards > Celcom', NOW(), NOW()),
(1236, 'Phone & Tablet > Prepaid Cards > Digi', NOW(), NOW()),
(1237, 'Phone & Tablet > Prepaid Cards > Hotlink', NOW(), NOW()),
(1238, 'Phone & Tablet > Prepaid Cards > Others', NOW(), NOW()),
(1239, 'Phone & Tablet > Prepaid Cards > Prepaid Plan', NOW(), NOW()),
(1240, 'Phone & Tablet > Prepaid Cards > TIMECel / Adam', NOW(), NOW()),
(1241, 'Phone & Tablet > Prepaid Cards > TM Touch', NOW(), NOW()),
(1242, 'Phone & Tablet > Accessories > Skin', NOW(), NOW()),
(1243, 'Home & Gardening > Gardening > Plants', NOW(), NOW()),
(1244, 'Home & Gardening > Gardening > Seeds', NOW(), NOW()),
(1245, 'Travel, Tours & Hotel > Ticket > Theme/Water Park', NOW(), NOW()),
(1246, 'Electronics & Appliances > Hand Tools', NOW(), NOW()),
(1247, 'Sports & Recreation > Fishing > Reel Rod Combo Set', NOW(), NOW()),
(1249, 'Services > Advertising', NOW(), NOW()),
(1250, 'Toys & Games > Remote Control Boat', NOW(), NOW()),
(1251, 'Music & Song > Instrument > Chinese Zither', NOW(), NOW()),
(1252, 'Arts, Antiques & Collectibles > Stamps > Antique', NOW(), NOW()),
(1253, 'Services > Creative Image', NOW(), NOW()),
(1254, 'Computer & Software > Hardware > Graphic Card > PCI-E', NOW(), NOW()),
(1255, 'Computer & Software > Hardware > Graphic Card > AGP', NOW(), NOW()),
(1257, 'Computer & Software > Hardware > Graphic Card > ISA / Others', NOW(), NOW()),
(1258, 'Food & Beverages > Dessert', NOW(), NOW()),
(1259, 'Home & Gardening > Staircase', NOW(), NOW()),
(1261, 'Home & Gardening > Wall Paper', NOW(), NOW()),
(1262, 'Movies & Video > Blu-Ray', NOW(), NOW()),
(1263, 'Computer & Software > Computer Storage > Blu-Ray', NOW(), NOW()),
(1264, 'Computer & Software > Hardware > Drive > Blu-Ray', NOW(), NOW()),
(1265, 'Computer & Software > Hardware > Memory > Server Ram', NOW(), NOW()),
(1267, 'Fashion > Men > Bag & Wallets > Wallet & Money Clips', NOW(), NOW()),
(1268, 'Toys & Games > Fast Food Toys > Snoopy', NOW(), NOW()),
(1269, 'Cars & Transport > Parts & Accessories > Steering Wheel Lock', NOW(), NOW()),
(1271, 'Sports & Recreation > Coaching & Training', NOW(), NOW()),
(1272, 'Services > Wedding Planner', NOW(), NOW()),
(1276, 'Baby, Kids, Mum > Strollers & Prams', NOW(), NOW()),
(1277, 'Baby, Kids, Mum > Feeding', NOW(), NOW()),
(1278, 'Baby, Kids, Mum > Diapering', NOW(), NOW()),
(1279, 'Baby, Kids, Mum > Bathing & Skincare', NOW(), NOW()),
(1280, 'Baby, Kids, Mum > Bedding', NOW(), NOW()),
(1281, 'Baby, Kids, Mum > Gear', NOW(), NOW()),
(1283, 'Baby, Kids, Mum > Furniture', NOW(), NOW()),
(1284, 'Baby, Kids, Mum > Others', NOW(), NOW()),
(1285, 'Sports & Recreation > Badminton', NOW(), NOW()),
(1286, 'Cars & Transport > Parts & Accessories > Vehicle Fuel Saver', NOW(), NOW()),
(1288, 'Phone & Tablet > Handphone > Blackberry', NOW(), NOW()),
(1289, 'Sports & Recreation > Tennis', NOW(), NOW()),
(1290, 'Health & Medical > Chinese Herbal', NOW(), NOW()),
(1291, 'Services > Entertainment', NOW(), NOW()),
(1292, 'B2B & Industrial Products > Agroculture', NOW(), NOW()),
(1293, 'Food & Beverages > Organic Food', NOW(), NOW()),
(1294, 'Learning & Education > Learning', NOW(), NOW()),
(1295, 'Learning & Education > Seminar & Training', NOW(), NOW()),
(1296, 'Cars & Transport > Window Tinting', NOW(), NOW()),
(1297, 'Services > Transcribing', NOW(), NOW()),
(1298, 'Services > Will Writing', NOW(), NOW()),
(1299, 'Fashion > Women > Muslimah > Hijabs & Tudung', NOW(), NOW()),
(1300, 'Cars & Transport > Cars > Chery', NOW(), NOW()),
(1301, 'Books & Comics > Feng Shui', NOW(), NOW()),
(1302, 'Books & Comics > Horoscope', NOW(), NOW()),
(1303, 'Office Equipment > Fax Machine', NOW(), NOW()),
(1305, 'Home & Gardening > Door > Door Lock', NOW(), NOW()),
(1307, 'Computer & Software > Hard Disk > SATA Hard Disk > 2.5\"', NOW(), NOW()),
(1309, 'Computer & Software > Hard Disk > SATA Hard Disk > 3.5\"', NOW(), NOW()),
(1310, 'Computer & Software > Hard Disk > IDE Hard Disk > 2.5\"', NOW(), NOW()),
(1311, 'Computer & Software > Hard Disk > IDE Hard Disk > 3.5\"', NOW(), NOW()),
(1312, 'Computer & Software > Hard Disk > 2.5\" Portable Hard Disk', NOW(), NOW()),
(1315, 'Computer & Software > Hard Disk > 3.5\" External Hard Disk', NOW(), NOW()),
(1316, 'Electronics & Appliances > Sewing Machine', NOW(), NOW()),
(1317, 'Services > Catering', NOW(), NOW()),
(1318, 'Services > Canopy', NOW(), NOW()),
(1319, 'Home & Gardening > Cookware', NOW(), NOW()),
(1320, 'Home & Gardening > Safe Box', NOW(), NOW()),
(1321, 'Camera & Camcorder > Photographs', NOW(), NOW()),
(1322, 'Food & Beverages > Seafood', NOW(), NOW()),
(1323, 'Electronics & Appliances > Home & Kitchen > Induction Cooker', NOW(), NOW()),
(1324, 'Phone & Tablet > Accessories > Apple iPhone', NOW(), NOW()),
(1325, 'Services > Insurance RoadTax Renewal', NOW(), NOW()),
(1326, 'Electronics & Appliances > Blue-ray Player', NOW(), NOW()),
(1327, 'Electronics & Appliances > Blu-ray Player', NOW(), NOW()),
(1328, 'Health & Medical > Face Mask', NOW(), NOW()),
(1329, 'Fashion > Men > Bag & Wallets > Waist Pouch', NOW(), NOW()),
(1330, 'Gifts & Premiums > Umbrella', NOW(), NOW()),
(1331, 'Electronics & Appliances > MP4 Player', NOW(), NOW()),
(1332, 'Fashion > Women > Intimate & Sleep > Bra & Bra Set', NOW(), NOW()),
(1333, 'Music & Song > Stage & Disco Lighting', NOW(), NOW()),
(1334, 'Music & Song > Sound & PA System', NOW(), NOW()),
(1335, 'Computer & Software > Hardware > Networking > Networking', NOW(), NOW()),
(1336, 'Computer & Software > Hardware > Networking > NAS', NOW(), NOW()),
(1338, 'Phone & Tablet > Handphone > Meizu', NOW(), NOW()),
(1339, 'Arts, Antiques & Collectibles > Anime Collectibles', NOW(), NOW()),
(1340, 'Phone & Tablet > Handphone > eTouch', NOW(), NOW()),
(1341, 'Services > Locksmith Services', NOW(), NOW()),
(1343, 'Camera & Camcorder > Photo Frame > Photo Frame', NOW(), NOW()),
(1344, 'Camera & Camcorder > Photo Frame > Digital Photo Frame', NOW(), NOW()),
(1345, 'Phone & Tablet > Handphone > Acer', NOW(), NOW()),
(1346, 'Fashion > Rainwear', NOW(), NOW()),
(1347, 'Sports & Recreation > Table Tennis', NOW(), NOW()),
(1348, 'House & Property > Hotel & Resort', NOW(), NOW()),
(1349, 'House & Property > Bungalow Land', NOW(), NOW()),
(1350, 'Rental, To Let & For Hire > Land', NOW(), NOW()),
(1351, 'Rental, To Let & For Hire > Condominium', NOW(), NOW()),
(1352, 'Rental, To Let & For Hire > Double Storey', NOW(), NOW()),
(1353, 'Rental, To Let & For Hire > Link House', NOW(), NOW()),
(1355, 'Rental, To Let & For Hire > Single Storey', NOW(), NOW()),
(1356, 'Rental, To Let & For Hire > Office Building', NOW(), NOW()),
(1358, 'Rental, To Let & For Hire > Factory', NOW(), NOW()),
(1359, 'Rental, To Let & For Hire > Warehouse', NOW(), NOW()),
(1360, 'Rental, To Let & For Hire > Flat', NOW(), NOW()),
(1361, 'Rental, To Let & For Hire > Town House', NOW(), NOW()),
(1362, 'Rental, To Let & For Hire > Villa', NOW(), NOW()),
(1363, 'Rental, To Let & For Hire > Hotel & Resort', NOW(), NOW()),
(1364, 'Rental, To Let & For Hire > Bangalow Land', NOW(), NOW()),
(1365, 'Arts, Antiques & Collectibles > Lighter', NOW(), NOW()),
(1368, 'Computer & Software > Tablet > Apple iPad', NOW(), NOW()),
(1369, 'Computer & Software > Tablet > Android Tablet', NOW(), NOW()),
(1370, 'Electronics & Appliances > Gadget > E-reader', NOW(), NOW()),
(1371, 'Electronics & Appliances > TV > LED TV', NOW(), NOW()),
(1372, 'Jobs & Freelances > Accounting, Tax, Audit, Co Sec', NOW(), NOW()),
(1373, 'Jobs  > Advertising, PR, Events Management', NOW(), NOW()),
(1374, 'Jobs  > Admin, Clerical', NOW(), NOW()),
(1375, 'Jobs  > Agriculture, Plantation, Fisheries', NOW(), NOW()),
(1376, 'Jobs  > Architecture, Interior Design, Construction', NOW(), NOW()),
(1377, 'Jobs  > Automotive, Aviation, Aerospace', NOW(), NOW()),
(1378, 'Jobs  > Banking, Finance, Insurance', NOW(), NOW()),
(1379, 'Jobs  > Biotech, Life Sciences', NOW(), NOW()),
(1380, 'Jobs  > Call Centre, CS, Tele Sales', NOW(), NOW()),
(1381, 'Jobs  > Education, Training', NOW(), NOW()),
(1382, 'Jobs  > Engineering', NOW(), NOW()),
(1383, 'Jobs  > Entertainment', NOW(), NOW()),
(1384, 'Jobs  > Food & Beverages, Hotel', NOW(), NOW()),
(1385, 'Jobs  > General Work', NOW(), NOW()),
(1386, 'Jobs  > Human Resource, Recruitment', NOW(), NOW()),
(1387, 'Jobs  > Legal, Law', NOW(), NOW()),
(1388, 'Jobs  > Logistics, Supply Chain, Warehousing', NOW(), NOW()),
(1389, 'Jobs  > Manufacturing', NOW(), NOW()),
(1390, 'Jobs  > Marketing', NOW(), NOW()),
(1391, 'Jobs  > Media, Broadcasting, Publishing', NOW(), NOW()),
(1392, 'Jobs  > Medical, Healthcare, Pharmaceutical', NOW(), NOW()),
(1393, 'Jobs  > Multimedia, Graphic Design', NOW(), NOW()),
(1394, 'Jobs  > Procurement', NOW(), NOW()),
(1395, 'Jobs  > Property, Real Estate', NOW(), NOW()),
(1396, 'Jobs  > Quality Assurance, QC, ISO', NOW(), NOW()),
(1397, 'Jobs  > Research & Development', NOW(), NOW()),
(1398, 'Jobs  > Retail, Trading, Distribution', NOW(), NOW()),
(1399, 'Jobs  > Sales', NOW(), NOW()),
(1400, 'Jobs  > Science & Technology', NOW(), NOW()),
(1401, 'Jobs  > Secretarial, PA', NOW(), NOW()),
(1402, 'Jobs  > Telecommunications', NOW(), NOW()),
(1403, 'Jobs  > Travel, Tourism', NOW(), NOW()),
(1404, 'Jobs  > Utilities', NOW(), NOW()),
(1405, 'Food & Beverages > Snack', NOW(), NOW()),
(1406, 'Electronics & Appliances > Ironing & Garment Steamer', NOW(), NOW()),
(1407, 'Health & Medical > Contact Lens', NOW(), NOW()),
(1408, 'Services > Others > Editing', NOW(), NOW()),
(1409, 'Internet > Broadband > Celcom', NOW(), NOW()),
(1410, 'Internet > Broadband > Digi', NOW(), NOW()),
(1411, 'Music & Song > Instrument > Trumpet', NOW(), NOW()),
(1412, 'Electronics & Appliances > Others', NOW(), NOW()),
(1414, 'Electronics & Appliances > iPod > Accessories', NOW(), NOW()),
(1415, 'Electronics & Appliances > iPod > Case', NOW(), NOW()),
(1416, 'Electronics & Appliances > iPod > Speaker Docks & System', NOW(), NOW()),
(1417, 'Home & Gardening > Decoration > Clock', NOW(), NOW()),
(1418, 'Phone & Tablet > Phone > Phone', NOW(), NOW()),
(1419, 'Phone & Tablet > Phone > Single Line', NOW(), NOW()),
(1424, 'Phone & Tablet > Phone System > PABX', NOW(), NOW()),
(1425, 'Phone & Tablet > Phone System > Trim Line / Hotel Phone', NOW(), NOW()),
(1426, 'Phone & Tablet > Phone System > Call Center', NOW(), NOW()),
(1427, 'Electronics & Appliances > Audio > Headphone > Headphone', NOW(), NOW()),
(1428, 'Electronics & Appliances > Audio > Headphone > In-ear', NOW(), NOW()),
(1429, 'Electronics & Appliances > Audio > Headphone > Over-ear', NOW(), NOW()),
(1430, 'Electronics & Appliances > Audio > Headphone > Cordless', NOW(), NOW()),
(1431, 'Electronics & Appliances > Audio > Headphone > Headset', NOW(), NOW()),
(1436, 'Fashion > Kids > Clothing > Muslimah', NOW(), NOW()),
(1437, 'Fashion > Women > Muslimah > Telekung', NOW(), NOW()),
(1439, 'Electronics & Appliances > Security System > Door Access', NOW(), NOW()),
(1440, 'Electronics & Appliances > Security System > Fire Alarm', NOW(), NOW()),
(1441, 'Books & Comics > Islam & Spirituality', NOW(), NOW());";

$sql[] = "
INSERT INTO ".DB_PREFIX."lelong_category (`category_id`, `name`, `create_time`, `last_update`) VALUES
(1442, 'Computer & Software > Tablet > Others', NOW(), NOW()),
(1443, 'Office Equipment > Refurbished Office Furniture', NOW(), NOW()),
(1444, 'Health & Medical > Thermometer', NOW(), NOW()),
(1446, 'Electronics & Appliances > A/V Accessories > Video Glasses', NOW(), NOW()),
(1447, 'Food & Beverages > Grains & Nuts', NOW(), NOW()),
(1448, 'Food & Beverages > Coffee', NOW(), NOW()),
(1449, 'Fashion > Fabric / Textile', NOW(), NOW()),
(1450, 'Toys & Games > Game Console > Nintendo > Nintendo Wii', NOW(), NOW()),
(1451, 'Toys & Games > Game Console > Nintendo > Nintendo DS', NOW(), NOW()),
(1452, 'Computer & Software > Tablet > Accessories', NOW(), NOW()),
(1453, 'Home & Gardening > Gardening > Gardening > Pot', NOW(), NOW()),
(1454, 'Computer & Software > Tablet > Blackberry Tablet', NOW(), NOW()),
(1455, 'Electronics & Appliances > iPod > iPod > Ipod Nano', NOW(), NOW()),
(1456, 'Electronics & Appliances > iPod > iPod > Ipod Touch', NOW(), NOW()),
(1457, 'Electronics & Appliances > iPod > iPod > Ipod Classic', NOW(), NOW()),
(1458, 'Electronics & Appliances > iPod > iPod > Ipod Shuffle', NOW(), NOW()),
(1459, 'Home & Gardening > Decoration > Vase', NOW(), NOW()),
(1460, 'Phone & Tablet > Handphone > Android Phone', NOW(), NOW()),
(1461, 'Home & Gardening > Pest & Weed Control', NOW(), NOW()),
(1463, 'Sports & Recreation > Hockey', NOW(), NOW()),
(1464, 'Phone & Tablet > Phone System > Telephone Voice Recording System', NOW(), NOW()),
(1466, 'Computer & Software > Software > Internet-based', NOW(), NOW()),
(1467, 'B2B & Industrial Products > Raw Materials > Soap', NOW(), NOW()),
(1468, 'Computer & Software > Services > Solutions', NOW(), NOW()),
(1471, 'Computer & Software > Computer Storage > HDD Docking', NOW(), NOW()),
(1472, 'Electronics & Appliances > MP5 Player', NOW(), NOW()),
(1473, 'Arts, Antiques & Collectibles > Craft > Crocheting & Knitting', NOW(), NOW()),
(1474, 'Computer & Software > Hardware > Monitors > Monitor Mounts & Stands', NOW(), NOW()),
(1475, 'Books & Comics > Children > Activity', NOW(), NOW()),
(1476, 'Books & Comics > Children > Junior Reference', NOW(), NOW()),
(1477, 'Books & Comics > Children > Board Books', NOW(), NOW()),
(1478, 'Books & Comics > Children > Play & Sound', NOW(), NOW()),
(1479, 'Books & Comics > Children > Art & Craft', NOW(), NOW()),
(1480, 'Cars & Transport > Cars > Lexus', NOW(), NOW()),
(1481, 'Rental, To Let & For Hire > Audio Visual > Sound System', NOW(), NOW()),
(1482, 'Home & Gardening > Home Improvement > Bathroom Accessories', NOW(), NOW()),
(1483, 'Jewellery & Accessories > Jewelry Sets', NOW(), NOW()),
(1486, 'Baby, Kids, Mum > Nursery Decor > Night Lights', NOW(), NOW()),
(1487, 'Computer & Software > Hard Disk > Solid-State Drives', NOW(), NOW()),
(1488, 'Home & Gardening > Water Heaters', NOW(), NOW()),
(1489, 'Phone & Tablet > Phone System > Keyphone Lightning Protection', NOW(), NOW()),
(1490, 'Rental, To Let & For Hire > Audio Visual > Televisions', NOW(), NOW()),
(1491, 'Beauty & Personal Care > Foot Care', NOW(), NOW()),
(1492, 'Phone & Tablet > Phone System > Others', NOW(), NOW()),
(1494, 'General & Misc > Construction Machinery', NOW(), NOW()),
(1497, 'Phone & Tablet > Handphone > Huawei', NOW(), NOW()),
(1498, 'Home & Gardening > Storage Boxes', NOW(), NOW()),
(1499, 'Home & Gardening > Home Improvement > Tile & Flooring', NOW(), NOW()),
(1501, 'B2B & Industrial Products > Chemical', NOW(), NOW()),
(1502, 'B2B & Industrial Products > Laboratory Equipment', NOW(), NOW()),
(1503, 'Home & Gardening > Decoration > Fountains', NOW(), NOW()),
(1505, 'Home & Gardening > Home Improvement > Hooks & Hangers', NOW(), NOW()),
(1506, 'Beauty & Personal Care > Skin Care > Lightening Cream', NOW(), NOW()),
(1508, 'Home & Gardening > Cleaning & Washing > Laundry Bags', NOW(), NOW()),
(1509, 'Beauty & Personal Care > Facial Care', NOW(), NOW()),
(1511, 'Services > Recording Studio', NOW(), NOW()),
(1512, 'Cars & Transport > Personal Watercraft > Accessories & Gear', NOW(), NOW()),
(1513, 'Beauty & Personal Care > Skin Care > Masks & Peels', NOW(), NOW()),
(1514, 'Arts, Antiques & Collectibles > Craft > Clay', NOW(), NOW()),
(1515, 'Food & Beverages > Fruit Juice', NOW(), NOW()),
(1516, 'Toys & Games > Game Console > Sony > Playstation Vita', NOW(), NOW()),
(1517, 'Home & Gardening > Bakeware', NOW(), NOW()),
(1518, 'B2B & Industrial Products > Printing > Presses', NOW(), NOW()),
(1519, 'Jewellery & Accessories > Costume Jewelry', NOW(), NOW()),
(1520, 'Phone & Tablet > Handphone > Lenovo', NOW(), NOW()),
(1521, 'B2B & Industrial Products > F & B Furniture', NOW(), NOW()),
(1522, 'Home & Gardening > Cleaning & Washing > Detergents', NOW(), NOW()),
(1523, 'Cars & Transport > Car Services', NOW(), NOW()),
(1525, 'Fashion > Men > Plus Size for Men', NOW(), NOW()),
(1526, 'Fashion > Women > Plus Size for Women', NOW(), NOW()),
(1527, 'Cars & Transport > Bicycle > Bicycle Accessories', NOW(), NOW()),
(1530, 'Sports & Recreation > Bicycle > Accessories', NOW(), NOW()),
(1531, 'Sports & Recreation > Accessories', NOW(), NOW()),
(1532, 'Phone & Tablet > Handphone > Ninetology', NOW(), NOW()),
(1533, 'Toys & Games > Game Console > Sony > Playstation 4', NOW(), NOW()),
(1534, 'Toys & Games > Remote Control Trucks', NOW(), NOW()),
(1536, 'Services > Business Outsourcing Services > Accounting & Finance', NOW(), NOW()),
(1537, 'Services > Business Outsourcing Services > Payroll Services', NOW(), NOW()),
(1538, 'Services > Business Outsourcing Services > Corporate Secretarial Services', NOW(), NOW()),
(1539, 'Services > Business Outsourcing Services > Audit', NOW(), NOW()),
(1540, 'Services > Business Outsourcing Services > Annual Tax Submission', NOW(), NOW()),
(1541, 'Toys & Games > Game Console > Nintendo > Nintendo 3DS', NOW(), NOW()),
(1542, 'Fashion > Costumes, Uniforms & Dancewear > Infants & Kids', NOW(), NOW()),
(1543, 'Fashion > Costumes, Uniforms & Dancewear > Men', NOW(), NOW()),
(1544, 'Fashion > Costumes, Uniforms & Dancewear > Women', NOW(), NOW()),
(1545, 'Fashion > Costumes, Uniforms & Dancewear > Mixed Items & Lots', NOW(), NOW()),
(1547, 'Fashion > Kids > Clothing > Tops & Tee', NOW(), NOW()),
(1548, 'Fashion > Kids > Clothing > Outerwear, Sweater and Hoodies', NOW(), NOW()),
(1549, 'Fashion > Kids > Clothing > Pants & Shorts', NOW(), NOW()),
(1550, 'Fashion > Kids > Clothing > Skirts & Skorts', NOW(), NOW()),
(1551, 'Fashion > Kids > Clothing > Legging and Tights', NOW(), NOW()),
(1552, 'Fashion > Kids > Clothing > Dress', NOW(), NOW()),
(1553, 'Fashion > Kids > Clothing > Suit & Vest', NOW(), NOW()),
(1554, 'Fashion > Kids > Clothing > Sets', NOW(), NOW()),
(1555, 'Fashion > Kids > Clothing > Jumpsuits & Rompers', NOW(), NOW()),
(1556, 'Fashion > Kids > Clothing > Jeans', NOW(), NOW()),
(1557, 'Fashion > Kids > Clothing > Underwear', NOW(), NOW()),
(1558, 'Fashion > Kids > Clothing > Pyjamas', NOW(), NOW()),
(1559, 'Fashion > Kids > Clothing > Traditional Wear', NOW(), NOW()),
(1560, 'Fashion > Kids > Accessories > Hair Accessories', NOW(), NOW()),
(1561, 'Fashion > Kids > Accessories > Hats & Caps', NOW(), NOW()),
(1562, 'Fashion > Kids > Accessories > Jewelry', NOW(), NOW()),
(1563, 'Fashion > Kids > Accessories > Socks', NOW(), NOW()),
(1564, 'Fashion > Kids > Accessories > Mixed Items and Lots', NOW(), NOW()),
(1565, 'Fashion > Kids > Accessories > Shoes - Boys', NOW(), NOW()),
(1566, 'Fashion > Kids > Accessories > Shoes - Girls', NOW(), NOW()),
(1567, 'Fashion > Kids > Accessories > Backpack and Bag', NOW(), NOW()),
(1568, 'Fashion > Kids > Accessories > Scarf', NOW(), NOW()),
(1569, 'Fashion > Baby > Accessories > Gloves & Mittens', NOW(), NOW()),
(1570, 'Fashion > Baby > Accessories > Hair Accessories', NOW(), NOW()),
(1571, 'Fashion > Baby > Accessories > Hats & Caps', NOW(), NOW()),
(1572, 'Fashion > Baby > Accessories > Jewelry', NOW(), NOW()),
(1573, 'Fashion > Baby > Accessories > Socks', NOW(), NOW()),
(1574, 'Fashion > Baby > Accessories > Mixed Items and Lots', NOW(), NOW()),
(1576, 'Fashion > Baby > Accessories > Shoes', NOW(), NOW()),
(1577, 'Fashion > Baby > Clothings > Tops & Tee', NOW(), NOW()),
(1578, 'Fashion > Baby > Clothings > Bottoms', NOW(), NOW()),
(1579, 'Fashion > Baby > Clothings > One Piece', NOW(), NOW()),
(1580, 'Fashion > Baby > Clothings > Outerwear & Sweater', NOW(), NOW()),
(1581, 'Fashion > Baby > Clothings > Dress', NOW(), NOW()),
(1582, 'Fashion > Baby > Clothings > Skirts', NOW(), NOW()),
(1583, 'Fashion > Baby > Clothings > Sleepwear', NOW(), NOW()),
(1584, 'Fashion > Baby > Clothings > Sets', NOW(), NOW()),
(1585, 'Fashion > Women > Muslimah > Baju Kurung', NOW(), NOW()),
(1586, 'Fashion > Women > Muslimah > Kaftans & Jubah', NOW(), NOW()),
(1587, 'Fashion > Women > Muslimah > Muslimah Tops', NOW(), NOW()),
(1588, 'Fashion > Women > Muslimah > Muslimah Dresses', NOW(), NOW()),
(1589, 'Fashion > Women > Muslimah > Muslimah Bottoms', NOW(), NOW()),
(1590, 'Fashion > Women > Muslimah > Mixed Item & Lots', NOW(), NOW()),
(1591, 'Fashion > Women > Handbag > Purses', NOW(), NOW()),
(1592, 'Fashion > Women > Handbag > Backpacks', NOW(), NOW()),
(1593, 'Fashion > Women > Handbag > Clutches & Envelope Bag', NOW(), NOW()),
(1594, 'Fashion > Women > Handbag > Shoulder Bag', NOW(), NOW()),
(1595, 'Fashion > Women > Handbag > Cross Body Bags & Sling Bags', NOW(), NOW()),
(1596, 'Fashion > Women > Handbag > Top Handle Bag', NOW(), NOW()),
(1597, 'Fashion > Women > Handbag > Wristlet', NOW(), NOW()),
(1598, 'Fashion > Women > Handbag > Cosmetics Bag', NOW(), NOW()),
(1599, 'Fashion > Women > Handbag > Mixed Items & Lots', NOW(), NOW()),
(1600, 'Fashion > Kids > Clothing > Muslimin', NOW(), NOW()),
(1601, 'Fashion > Women > Shoes > Sports', NOW(), NOW()),
(1602, 'Fashion > Women > Shoes > Casual', NOW(), NOW()),
(1603, 'Fashion > Women > Shoes > Formal', NOW(), NOW()),
(1604, 'Fashion > Women > Shoes > Slippers', NOW(), NOW()),
(1605, 'Fashion > Women > Shoes > Mixed Items & Lots', NOW(), NOW()),
(1606, 'Fashion > Women > Maternity > Dresses', NOW(), NOW()),
(1607, 'Fashion > Women > Maternity > Legging & Jegging', NOW(), NOW()),
(1608, 'Fashion > Women > Maternity > Nursing', NOW(), NOW()),
(1609, 'Fashion > Women > Maternity > Sets (Top & Bottom)', NOW(), NOW()),
(1610, 'Fashion > Women > Maternity > Panties', NOW(), NOW()),
(1611, 'Fashion > Women > Maternity > Pants', NOW(), NOW()),
(1612, 'Fashion > Women > Maternity > Shorts', NOW(), NOW()),
(1613, 'Fashion > Women > Maternity > Top & Tee', NOW(), NOW()),
(1614, 'Fashion > Women > Maternity > Shirt & Blouses', NOW(), NOW()),
(1615, 'Fashion > Women > Maternity > Cardigans, Sweater & Hoodies', NOW(), NOW()),
(1616, 'Fashion > Women > Maternity > Swimwear', NOW(), NOW()),
(1618, 'Fashion > Women > Hosiery Socks > Pantyhose & Thigh', NOW(), NOW()),
(1619, 'Fashion > Women > Hosiery Socks > Socks & Leg Warmer', NOW(), NOW()),
(1620, 'Fashion > Women > Hosiery Socks > Stocking & Things Highs', NOW(), NOW()),
(1621, 'Fashion > Women > Hosiery Socks > Mixed Items and Lots', NOW(), NOW()),
(1622, 'Fashion > Women > Intimate & Sleep > Slips', NOW(), NOW()),
(1623, 'Fashion > Women > Intimate & Sleep > Shapewears', NOW(), NOW()),
(1625, 'Fashion > Women > Accessories > Collar Tips', NOW(), NOW()),
(1626, 'Fashion > Women > Accessories > Mixed Items & Lots', NOW(), NOW()),
(1627, 'Fashion > Women > Accessories > Gloves & Mittens', NOW(), NOW()),
(1628, 'Fashion > Women > Accessories > Handkerchiefs', NOW(), NOW()),
(1629, 'Fashion > Women > Accessories > Wigs & Hair Extention', NOW(), NOW()),
(1631, 'Fashion > Women > Accessories > Card & Documents Holder', NOW(), NOW()),
(1633, 'Fashion > Women > Clothing > Sports Apparel', NOW(), NOW()),
(1635, 'Fashion > Men > Clothing > Coats & Jackets', NOW(), NOW()),
(1636, 'Fashion > Men > Clothing > Jeans', NOW(), NOW()),
(1637, 'Fashion > Women > Clothing > Jumpsuits and Rompers', NOW(), NOW()),
(1638, 'Fashion > Women > Clothing > Shorts', NOW(), NOW()),
(1639, 'Fashion > Women > Clothing > Top & Tee', NOW(), NOW()),
(1640, 'Fashion > Women > Clothing > Sweater & Hoodie', NOW(), NOW()),
(1641, 'Fashion > Women > Clothing > Cardigans', NOW(), NOW()),
(1642, 'Fashion > Women > Clothing > Blazer', NOW(), NOW()),
(1643, 'Fashion > Women > Clothing > Cheong Sam', NOW(), NOW()),
(1644, 'Fashion > Women > Clothing > Mixed Items and Lots', NOW(), NOW()),
(1645, 'Fashion > Men > Clothing > Shirts', NOW(), NOW()),
(1646, 'Fashion > Men > Clothing > Blazer', NOW(), NOW()),
(1647, 'Fashion > Men > Clothing > Pants', NOW(), NOW()),
(1648, 'Fashion > Men > Clothing > Shorts', NOW(), NOW()),
(1649, 'Fashion > Men > Clothing > Socks', NOW(), NOW()),
(1650, 'Fashion > Men > Clothing > Sweater & Hoodie', NOW(), NOW()),
(1651, 'Fashion > Men > Clothing > Cardigans', NOW(), NOW()),
(1652, 'Fashion > Men > Clothing > Swimwear', NOW(), NOW()),
(1653, 'Fashion > Men > Bag & Wallets > Messenger Bag', NOW(), NOW()),
(1654, 'Fashion > Men > Bag & Wallets > Briefcase', NOW(), NOW()),
(1655, 'Fashion > Men > Bag & Wallets > Backpack', NOW(), NOW()),
(1656, 'Fashion > Men > Bag & Wallets > Duffel Bag', NOW(), NOW()),
(1657, 'Fashion > Men > Muslimim > Baju Melayu', NOW(), NOW()),
(1658, 'Fashion > Men > Muslimim > Jubah', NOW(), NOW()),
(1659, 'Fashion > Men > Muslimim > Batik Tops', NOW(), NOW()),
(1660, 'Fashion > Men > Muslimim > Sarong', NOW(), NOW()),
(1661, 'Fashion > Men > Muslimim > Songkok', NOW(), NOW()),
(1662, 'Fashion > Men > Muslimim > Mixed Items & Lots', NOW(), NOW()),
(1663, 'Fashion > Men > Shoes > Boots', NOW(), NOW()),
(1664, 'Fashion > Men > Shoes > Formal', NOW(), NOW()),
(1665, 'Fashion > Men > Shoes > Occupational (Safety Shoe)', NOW(), NOW()),
(1666, 'Fashion > Men > Shoes > Sandals & Flip Flops', NOW(), NOW()),
(1667, 'Fashion > Men > Shoes > Slippers', NOW(), NOW()),
(1668, 'Fashion > Men > Shoes > Mixed Items & Lots', NOW(), NOW()),
(1669, 'Fashion > Men > Accessories > Collar Tips & Cufflinks', NOW(), NOW()),
(1670, 'Fashion > Men > Accessories > Gloves & Mittens', NOW(), NOW()),
(1671, 'Fashion > Men > Accessories > Wigs & Hairpieces', NOW(), NOW()),
(1672, 'Fashion > Men > Accessories > Handkerchiefs', NOW(), NOW()),
(1673, 'Fashion > Men > Accessories > Hats, Cap & Beanie', NOW(), NOW()),
(1674, 'Fashion > Men > Accessories > Card & Documents Holder', NOW(), NOW()),
(1675, 'Fashion > Men > Accessories > Key Chains', NOW(), NOW()),
(1676, 'Fashion > Men > Accessories > Scarf', NOW(), NOW()),
(1677, 'Fashion > Men > Accessories > Eyewear', NOW(), NOW()),
(1679, 'Fashion > Men > Jewelry > Bracelets & Wristband', NOW(), NOW()),
(1680, 'Fashion > Men > Jewelry > Necklaces & Pendants', NOW(), NOW()),
(1681, 'Fashion > Men > Jewelry > Earring & Studs', NOW(), NOW()),
(1682, 'Fashion > Men > Jewelry > Rings & Toe Rings', NOW(), NOW()),
(1683, 'Fashion > Men > Jewelry > Mixed Items', NOW(), NOW()),
(1684, 'Phone & Tablet > Handphone > Xiaomi', NOW(), NOW()),
(1685, 'B2B & Industrial Products > Cleaning Equipment', NOW(), NOW()),
(1688, 'Cars & Transport > Parts & Accessories > Batteries & Cables', NOW(), NOW()),
(1689, 'Phone & Tablet > Prepaid Cards > U Mobile', NOW(), NOW()),
(1691, 'Office Equipment > Office Supplies > Labels', NOW(), NOW()),
(1692, 'Internet > Broadband > U Mobile', NOW(), NOW()),
(1693, 'Phone & Tablet > Handphone > Oppo', NOW(), NOW()),
(1694, 'Fashion > Women > Clothing > Saree', NOW(), NOW()),
(1695, 'Sports & Recreation > Sepak Takraw', NOW(), NOW()),
(1696, 'Home & Gardening > Home Decor > Home Fragrances', NOW(), NOW()),
(1697, 'Electronics & Appliances > Audio > DAC', NOW(), NOW()),
(1698, 'Phone & Tablet > Handphone > Coolpad', NOW(), NOW()),
(1699, 'Sports & Recreation > Swimming', NOW(), NOW()),
(1700, 'Cars & Transport > Parts & Accessories > Apparel & Merchandise', NOW(), NOW()),
(1701, 'Computer & Software > Hardware > Memory > DDR4 RAM', NOW(), NOW()),
(1702, 'Sports & Recreation > Dart Set > Accessories', NOW(), NOW()),
(1703, 'House & Property > Semi-D', NOW(), NOW()),
(1704, 'House & Property > 3 Storey', NOW(), NOW()),
(1705, 'Sports & Recreation > Dodgeball', NOW(), NOW()),
(1707, 'Phone & Tablet > Wearable Devices > Smart Watches', NOW(), NOW()),
(1708, 'Phone & Tablet > Wearable Devices > Smart Bands', NOW(), NOW()),
(1709, 'Services > Others > Physiotherapy', NOW(), NOW()),
(1710, 'Phone & Tablet > Handphone > Doo-Gee', NOW(), NOW()),
(1711, 'Books & Comics > Animation', NOW(), NOW()),
(1712, 'Pet Supplies > Supplements & Vitamins', NOW(), NOW()),
(1713, 'Fashion > Kids > Accessories > Shoes - Unisex', NOW(), NOW()),
(1714, 'Fashion > Men > Shoes > Sneakers', NOW(), NOW()),
(1715, 'Fashion > Women > Shoes > Sneakers', NOW(), NOW()),
(1716, 'Fashion > Women > Accessories > Wedding', NOW(), NOW()),
(1717, 'Fashion > Women > Clothing > Wedding Gown', NOW(), NOW()),
(1718, 'Fashion > Women > Shoes > Wedding', NOW(), NOW()),
(1719, 'Electronics & Appliances > Home & Kitchen > Juicers', NOW(), NOW());";
?>